### ISSUE TITLE
Message: Error looking up function 'libvlc_media_player_stop': Die angegebene Prozedur wurde nicht gefunden.

### ISSUE THREAD

**Issue by klaro00** [caprica/vlcj#1030]
I'm trying to run the "VlcjJavaFxApplication" example on Win10, Java 15, getting this error message:

```
Error looking up function 'libvlc_media_player_stop': Die angegebene Prozedur wurde nicht gefunden.
```

I tried various version combinations of vlcj itself and vlc-4 with no success, including the latest vlcj version available via Maven dependecy (4.7.0), and the latest VLC 4 nighly build (as of Dec 17 - 20201217-0422, 64 bit).

A short look into vlcj source code shows that the error occurs in class "LibVlcVersion", method "LibVlcVersion()":

```
public LibVlcVersion() {
    this.actualVersion = new Version(libvlc_get_version());                   <== This line fails
    this.changeset = libvlc_get_changeset();
}
```

I believe it's rather a problem loading libvlc.dll than a problem with the line showed above, since this line is the first which calls the DLL (I think).

Because the behaviour is the same no matter which versions I use I might miss something general. I can confirm that the VLC location is read from the "nativeDirectory" entry in file "vlcj.config".

Any clues?

The full stack trace ist as follows:

```
Error looking up function 'libvlc_media_player_stop': Die angegebene Prozedur wurde nicht gefunden.

Exception in Application constructor
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.RuntimeException: Unable to construct Application instance: class de.klaro.convision.app.VlcjJavaFxApplication
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
    at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:802)
    at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
    at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
    at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    ... 1 more
Caused by: uk.co.caprica.vlcj.factory.NativeLibraryMappingException: Failed to properly initialise the native library
    at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:184)
    at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108)
    at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:163)
    at de.klaro.convision.app.VlcjJavaFxApplication.<init>(VlcjJavaFxApplication.java:36)
    ... 14 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.LibVlc
    at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49)
    at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:195)
    at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:181)
    ... 17 more
Exception running application de.klaro.convision.app.VlcjJavaFxApplication

Process finished with exit code 1
```

**Comment by klaro00** [comment]
I retried using branches "master" of vlcj and vlcj-natives, now the example is working.

It would be nice to know which nightly build is working with a tagged version. Maybe you can document this so one can download the correct (matching) VLC version.

I'm closing this issue.

Cheers, Klaus

**Comment by caprica** [comment]
The only answer for pre-release software is "use the latest version".
