### ISSUE TITLE
Issue with NativeDiscovery in MacOS

### ISSUE THREAD

**Issue by Abu-Abdullah** [caprica/vlcj#1038]
I have tried today vlcj in MacOS 10.15.3 with SNAPSHOT 5.0.0 and [vlc 4](https://artifacts.videolan.org/vlc/nightly-macos-x86_64/20210127-0413/vlc-4.0.0-dev-intel64-25ca0144.dmg)

i got this error:
```
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
java.lang.UnsatisfiedLinkError: Unable to load library 'vlc':
dlopen(libvlc.dylib, 9): image not found
dlopen(libvlc.dylib, 9): image not found
dlopen(/Users/oracle/Library/Frameworks/vlc.framework/vlc, 9): image not found
dlopen(/Library/Frameworks/vlc.framework/vlc, 9): image not found
dlopen(/System/Library/Frameworks/vlc.framework/vlc, 9): image not found
Native library (darwin/libvlc.dylib) not found in resource path (AudioCataloger.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Native.register(Native.java:1722)
	at com.sun.jna.Native.register(Native.java:1443)
	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:109)
	at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:195)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:181)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at com.myapp.JVLC.<init>(Unknown Source)
	at com.myapp.AudioCataloger.start(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libvlc.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 17 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libvlc.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 17 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/oracle/Library/Frameworks/vlc.framework/vlc, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 17 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/vlc.framework/vlc, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 17 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/vlc.framework/vlc, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 17 more
	Suppressed: java.io.IOException: Native library (darwin/libvlc.dylib) not found in resource path (AudioCataloger.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 17 more
2021-02-19 16:55:50.383 java[632:9210] CGLChoosePixelFormat: No matching pixel format exists for the requested attributes, trying again with limited capabilities
2021-02-19 16:55:50.659 java[632:9210] CGLChoosePixelFormat: No matching pixel format exists for the requested attributes, trying again with limited capabilities
2021-02-19 16:56:02.525 java[632:9210] CGLChoosePixelFormat: No matching pixel format exists for the requested attributes, trying again with limited capabilities
```
libvlc.dylib is in:
/Applications/VLC.app/Contents/Frameworks/

**Comment by caprica** [comment]
Did you install VLC normally using an official package?

**Comment by Abu-Abdullah** [comment]
yes, i just got it from:
https://artifacts.videolan.org/vlc/nightly-macos-x86_64/20210127-0413/vlc-4.0.0-dev-intel64-25ca0144.dmg

**Comment by caprica** [comment]
So VLC 4.0.0 doesn't have any official release yet of course, but your error is the usual problem of non-working discovery.

There is nothing new to add on this issue really - make sure you have a 64-bit version of VLC, make sure VLC is installed correctly, follow this https://capricasoftware.co.uk/projects/vlcj-4/tutorials/first-steps, check other issues in this repo relating to macOS native discovery...

When VLC 4.0.0 final is released, I will make sure the out-of-the-box vlcj 5.0.0 works with it, assuming VLC is properly installed by an official package.

I think I have had vlcj-5.0.0 SNAPSHOT working on macOS, but that was before the latest major OS release.

**Comment by caprica** [comment]
What you might try, is the latest vlcj native discovery allows you to specify the location of the native library using a config file:
```
~/.config/vlcj/vlcj.config
```
You specify e.g.:
```
nativeDirectory=/Applications/VLC.app/Contents/Frameworks
```
Assuming that directory is what contains the dylib file(s).

**Comment by Abu-Abdullah** [comment]
thank you @caprica 
I tried to set the path manually ```NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "/Applications/VLC.app/Contents/Frameworks");``` without success
```
java.lang.UnsatisfiedLinkError: Unable to load library 'vlc':
dlopen(/Applications/VLC.app/Contents/Frameworks/libvlc.dylib, 9): Library not loaded: @rpath/libvlccore.dylib
  Referenced from: /Applications/VLC.app/Contents/Frameworks/libvlc.12.dylib
  Reason: image not found
dlopen(/Applications/VLC.app/Contents/Frameworks/libvlc.dylib, 9): Library not loaded: @rpath/libvlccore.dylib
  Referenced from: /Applications/VLC.app/Contents/Frameworks/libvlc.12.dylib
  Reason: image not found
dlopen(/Users/oracle/Library/Frameworks/vlc.framework/vlc, 9): image not found
dlopen(/Library/Frameworks/vlc.framework/vlc, 9): image not found
dlopen(/System/Library/Frameworks/vlc.framework/vlc, 9): image not found
```

i will try few things and see

**Comment by Abu-Abdullah** [comment]
I just returned back to the old 3.0.12 and it works
i guess we can test the new one once it is launched

**Comment by caprica** [comment]
Can you spot if there are any differences in the installation directory structure if you compare your VLC 3.x installation with your VLC 4.x installation?

**Comment by Abu-Abdullah** [comment]
vlc 3
/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib

vlc 4
/Applications/VLC.app/Contents/Frameworks/libvlc.dylib

even the plugins is in different locations

**Comment by caprica** [comment]
Thanks for that, can you also please show the same thing for the difference in plugin locations?

**Comment by Abu-Abdullah** [comment]
vlc 3
/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib
/Applications/VLC.app/Contents/MacOS/plugins/

vlc 4
/Applications/VLC.app/Contents/Frameworks/libvlc.dylib
/Applications/VLC.app/Contents/Frameworks/plugins/

**Comment by caprica** [comment]
Thanks. It might be quite straightforward to tweak the discovery mechanism to look in that folder.

See: 61c2998f4e25b618407ddabad01848205cafe5b1 and 941b3b687a797f699402ef5e32d9f63eaf3ff2ce

There is no release build yet, but if you clone the projects you could try and see if this change works.

**Comment by caprica** [comment]
I pushed a new 5.0.0-SNAPSHOT release with this change to GitHub packages and the Maven snapshot repo.

**Comment by caprica** [comment]
If this change doesn't work, then there is something else wrong/different and it would require further investigation, but that will have to wait until the final release is ready I'm afraid. macOS just isn't high on my list of priorities right now.

**Comment by Abu-Abdullah** [comment]
now i got this
```
Error looking up function 'libvlc_video_get_spu_text_scale': dlsym(0x7fb09dc1be60, libvlc_video_get_spu_text_scale): symbol not found
uk.co.caprica.vlcj.factory.NativeLibraryMappingException: Failed to properly initialise the native library
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:184)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at com.myapp.JVLC.<init>(Unknown Source)
	at com.myapp.AudioCataloger.start(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.LibVlc
	at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:195)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:181)
	... 10 more

```

**Comment by caprica** [comment]
The pre-release build of VLC 4.x that you're using is not recent enough, libvlc_video_get_spu_text_scale is quite new.

**Comment by caprica** [comment]
At least now the native discovery is finding the native libraries.

**Comment by Abu-Abdullah** [comment]
i just pick up a newer version and now there is this error:
```
Unknown vlc configuration variable named vmem-chroma
Assertion failed: (p_config != NULL), function config_GetPsz, file /Users/videolan/builds/_8sxWuKU/0/videolan/vlc/extras/package/macosx/../../../src/config/core.c, line 128.
```


i think the nightly builds are not freezed and a lot of structuring is happening at the same time. maybe following these builds errors is time consuming now.

thank you for your usual support

**Comment by caprica** [comment]
That's yet another different error and I'm afraid it might not be something you can resolve until a new (or even release) build.

But for me, the original issue is resolved isn't it? The discovery itself now works with the change I made.
