### ISSUE TITLE
Help With Custom Native Discovery

### ISSUE THREAD

**Issue by PulseBeat02** [caprica/vlcj#1040]
Hi, I was wondering if I could receive some help with implementing a custom native discovery method for VLCJ. I wanted to make my application download prebuilt binaries of VLC based on the Operating System into a "vlc" folder, which would then be extracted. Then, I would use a custom search method to locate the plugins folder of the binaries and set the path to that.

I managed to get the downloading and prebuilt binaries done. However, I am having some issues relating to searching and setting the vlc environment path. My current implementation looks like so:

```
import org.jetbrains.annotations.NotNull;
import uk.co.caprica.vlcj.binding.LibC;
import uk.co.caprica.vlcj.factory.discovery.strategy.NativeDiscoveryStrategy;

import java.io.File;
import java.util.ArrayDeque;
import java.util.Arrays;
import java.util.Queue;

public class EnchancedNativeDiscovery implements NativeDiscoveryStrategy {

  private final String dir;
  private String path;

  /** Instantiates a new EnchancedNativeDiscovery */
  public EnchancedNativeDiscovery(@NotNull final String dir) {
    this.dir = dir;
  }

  /** Returns whether the strategy is supported */
  @Override
  public boolean supported() {
    return true;
  }

  /**
   * Attempts to discover VLC installation downloaded from pre-compiled binaries.
   *
   * @return String discovered path, null if not found.
   */
  @Override
  public String discover() {
    final File fold = new File(dir);
    if (!fold.exists()) {
      return null;
    }
    final Queue<File> folders = new ArrayDeque<>(Arrays.asList(fold.listFiles()));
    while (!folders.isEmpty()) {
      final File f = folders.remove();
      if (f.isDirectory()) {
        if (f.getName().equals("plugins")) {
          path = f.getAbsolutePath();
          onSetPluginPath(path);
          return path;
        }
        folders.addAll(Arrays.asList(f.listFiles()));
      }
    }
    return null;
  }

  /**
   * Ran once path is found.
   *
   * @param s path
   * @return found
   */
  @Override
  public boolean onFound(final String s) {
    return true;
  }

  /**
   * Ran once plugin path is set.
   *
   * @param s path
   * @return found
   */
  @Override
  public boolean onSetPluginPath(final String s) {
    return LibC.INSTANCE.setenv("VLC_PLUGIN_PATH", path, 1) == 0;
  }

  public String getDir() {
    return dir;
  }

  public String getPath() {
    return path;
  }
}
```

Basically, after I download the folder, I recursively search for the /plugins folder. I saw that in the built-in native searches try to find the /plugins folder (as an example take a look [https://github.com/caprica/vlcj/blob/941b3b687a797f699402ef5e32d9f63eaf3ff2ce/src/main/java/uk/co/caprica/vlcj/factory/discovery/strategy/LinuxNativeDiscoveryStrategy.java#L36](here)). I tried to implement that solution here, and the finding seemed to work, however, during the call on the onSetPluginPath, I had some issues. I got an UnsatisifiedLinkError when executing this method. The error looked like this:

```
[ERROR] .... Error occurred while enabling DeluxeMediaPlugin v1.0.0 (Is it up to date?)
java.lang.UnsatisfiedLinkError: com.github.pulsebeat02.jna.Native.getNativeVersion()Ljava/lang/String;
at com.github.pulsebeat02.jna.Native.getNativeVersion(Native Method) ~[?:?]
at com.github.pulsebeat02.jna.Native.<clinit>(Native.java:197) ~[?:?]
at com.github.pulsebeat02.vlcj.binding.LibVlc.<clinit>(LibVlc.java:98) ~[?:?]
at com.github.pulsebeat02.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49) ~[?:?]
at com.github.pulsebeat02.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:195) ~[?:?]
at com.github.pulsebeat02.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:181) ~[?:?]
at com.github.pulsebeat02.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108) ~[?:?]
at com.github.pulsebeat02.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:163) ~[?:?]
at com.github.pulsebeat02.minecraftmedialibrary.MinecraftMediaLibrary.dependencyTasks(MinecraftMediaLibrary.java:135) ~[?:?]
at com.github.pulsebeat02.minecraftmedialibrary.MinecraftMediaLibrary.<init>(MinecraftMediaLibrary.java:82) ~[?:?]
at com.github.pulsebeat02.deluxemediaplugin.DeluxeMediaPlugin.onEnable(DeluxeMediaPlugin.java:58) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-526]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-526]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-526]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-526]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-526]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:213) ~[patched_1.16.5.jar:git-Paper-526]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941) ~[patched_1.16.5.jar:git-Paper-526]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-526]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
(I shaded and relocated the paths for VLCJ) I suspected it's possibly some flaw in my code that is causing this. Or another possible cause is that the plugins folder that I had didn't contain the necessary library that was needed to be loaded. According to line 98 on LibVLC, it was this method:

```
public static native libvlc_module_description_t libvlc_audio_filter_list_get(libvlc_instance_t var0);
```

So that is why I suspected it could be an issue relating to the native library not existing. Do you have any suggestions on how I could solve this?

**Comment by caprica** [comment]
How can you include a sharded JNA (with different package names) when it has its own JNI library that it uses?

**Comment by caprica** [comment]
What I mean is, the JNA classes are in package com.sun.jna with various JNI bindings to a native library that expects the same package names. So it can't find com.github.pulsebeat02.jna.Native.getNativeVersion *native method* in any native library (like the JNA JNIDispatch library, if I got the name right).

**Comment by PulseBeat02** [comment]
Ah, I see. So that means I shouldn't relocate the jar, but instead leave the normal package conventions right?

**Comment by caprica** [comment]
For JNA, yes.

Honestly, I struggle to see why sharding jars is that important. Sure, it's nice to just drop one file in when you install something, but does anyone really care.

**Comment by PulseBeat02** [comment]
I see. Thank you for the response and help.
