### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Unable to load library 'libvlc

### ISSUE THREAD

**Issue by YazdanNA** [caprica/vlcj#1072]
I want to use this lib but when I use it i get following errer, please help me.

code:

```
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class Vlc {

    public static void main(String[] args)
    {
        EmbeddedMediaPlayerComponent component = new EmbeddedMediaPlayerComponent();

        JFrame frame = new JFrame("Media");
        frame.setContentPane(component);
        frame.setBounds(new Rectangle(200,200,800,600));
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
               component.release();
               System.exit(0);
            }
        });

        frame.setVisible(true);
        component.mediaPlayer().media().play("E:\\AudioVideo.mp4");
    }
}





output:

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'libvlc':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/libvlc.dll) not found in resource path (C:\Users\Pishgaman\IdeaProjects\VLCMedia\out\production\VLCMedia;C:\Users\Pishgaman\Downloads\jar_files\jna-5.2.0.jar;C:\Users\Pishgaman\Downloads\jar_files\jna-platform-5.2.0.jar;C:\Users\Pishgaman\Downloads\jar_files\vlcj-4.7.1.jar;C:\Users\Pishgaman\Downloads\jar_files\vlcj-natives-4.1.0.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Native.register(Native.java:1716)
	at com.sun.jna.Native.register(Native.java:1437)
	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:98)
	at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:195)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:181)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent.initMediaPlayerFactory(EmbeddedMediaPlayerComponent.java:116)
	at uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent.<init>(EmbeddedMediaPlayerComponent.java:77)
	at uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent.<init>(EmbeddedMediaPlayerComponent.java:111)
	at Vlc.main(Vlc.java:12)
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 13 more
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 13 more
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:265)
		... 13 more
	Suppressed: java.io.IOException: Native library (win32-x86-64/libvlc.dll) not found in resource path (C:\Users\Pishgaman\IdeaProjects\VLCMedia\out\production\VLCMedia;C:\Users\Pishgaman\Downloads\jar_files\jna-5.2.0.jar;C:\Users\Pishgaman\Downloads\jar_files\jna-platform-5.2.0.jar;C:\Users\Pishgaman\Downloads\jar_files\vlcj-4.7.1.jar;C:\Users\Pishgaman\Downloads\jar_files\vlcj-natives-4.1.0.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1089)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 13 more
```

**Comment by caprica** [comment]
Read through all of this... ;-)

https://github.com/caprica/vlcj/search?q=java.lang.UnsatisfiedLinkError&type=issues

**Comment by YazdanNA** [comment]
right 
but I want use this without install vlcPlayer how I do this?
thanks

**Comment by YazdanNA** [comment]
I have no problem when I use vlc but I want to use libvlc library directly please help me I am  beginner in this work.

**Comment by caprica** [comment]
You must install VLC. Or if you're on Windows you could maybe copy *all* of the DLLs from your VLC installation and plugins directory and use vlcj's native discovery mechanism (read the Javadoc or the tutorials) to find those files.

Your life will be a lot simpler if you just install VLC.

**Comment by YazdanNA** [comment]
I'm working on a program and if I want to publish my final product across multiple platforms does this method work well ?

**Comment by caprica** [comment]
Unfortunately, no it doesn't. You can't copy shared objects on Linux or dylibs on macOS from one distribution to some arbitrary directory on some other distribution.

On Linux, you could create an installation package that declared a dependency on VLC or libvlc and that should work.

On macOS, I don't know the solution. I don't use macOS (much).

But really, you would be OK with insisting as a prerequisite that a JVM was installed, but not VLC? That doesn't make much sense to me.

**Comment by YazdanNA** [comment]
Yes, you are absolutely right, if there was a way to break this dependence, it would be very good, but still no problem, thank you for taking the time
