### ISSUE TITLE
ExceptionInInitializerError on Android

### ISSUE THREAD

**Issue by Ali-RS** [caprica/vlcj#1091]
Hi

I am getting this error when trying to use Vlcj on Android.

Error log:

 ```
SEVERE Exception thrown in Thread[GLThread 141,5,main]
 java.lang.ExceptionInInitializerError
 	at uk.co.caprica.vlcj.binding.LibVlc.libvlc_get_version(Native Method)
 	at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49)
 	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:195)
 	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:181)
 	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108)
 	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:163)
 	at mygame.Main.testVlcj(Main.java:98)
 	at mygame.Main.simpleInitApp(Main.java:86)
 	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:240)
 	at com.jme3.app.AndroidHarnessFragment.initialize(AndroidHarnessFragment.java:555)
 	at com.jme3.system.android.OGLESContext.onDrawFrame(OGLESContext.java:342)
 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
 Caused by: java.lang.IllegalStateException: The SecurityManager implementation on this platform is broken; you must explicitly provide the class to register
 	at com.sun.jna.Native.getCallingClass(Native.java:1481)
 	at com.sun.jna.Native.register(Native.java:1437)
 	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:98)
 	... 13 more
 
```
Using vlcj 4.7.1

I am adding these dependencies in the `build.gradle` file:

```
dependencies {

    ...

    // https://mvnrepository.com/artifact/uk.co.caprica/vlcj
    implementation (group: 'uk.co.caprica', name: 'vlcj', version: '4.7.1') {
            exclude module: 'jna'
            exclude module: 'jna-platform'
    }
    // Add jna android specific builds, see: https://github.com/java-native-access/jna/blob/master/www/FrequentlyAskedQuestions.md#jna-on-android
    implementation 'net.java.dev.jna:jna:5.2.0@aar'
    // Add Libvlc android natives
    implementation 'org.videolan.android:libvlc-all:3.4.3'
    
}
```

Regards

**Comment by CrackerKSR** [comment]
I think this lib uses awt, swing and all which is are not supported by android

**Comment by caprica** [comment]
That is not wrong, but this ticket is over a year old :-)
