### ISSUE TITLE
VLCJ not working on Apple M1 Chip (Arm64)

### ISSUE THREAD

**Issue by dramms** [caprica/vlcj#1102]
Hello everyone,

I am currently adding support for the M1 chip from Apple to an existing application, but unfortunately VLCJ won't work.

I’m using:
- Java 17.0.1 for arm64 (Amazon Corretto)
- VLC 3.0.16 for arm64
- VLCJ 4.7.1
- JNA 5.10.0
- The application is compiled against Java 8

### Case 1: Trying to start the application with distributing VLC myself.
I‘m distributing the VLC files with the application and letting VLCJ load the libraries from a given path from the file system using the NativeDiscoveryStrategy. In this case, the library is loaded successfully, but the application crashes when calling an API from VLC, like

`uk.co.caprica.vlcj.player.embedded.embeddedMediaPlayer.media().prepare(…) `

### Case 2: Trying to start the application with an installed version of VLC.
I’m adding a new NativeDiscoveryStrategy to the lib folder of the installation:

> /Applications/VLC.app/Contents/MacOS/lib/

When starting the application, the following exception is thrown:

> Failed to get a new native library instance
> java.lang.RuntimeException: Failed to get a new native library instance
> at uk.co.caprica.vlcj.factory.MediaPlayerFactory.newLibVlcInstance(MediaPlayerFactory.java:214) ~[vlcj-4.7.1.jar:?]
> at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:110) ~[vlcj-4.7.1.jar:?]
> at my.code.class(class.java:123)
> at java.lang.Thread.run(Thread.java:833) [?:?] 

----------

My preferred use case is the first one, but maybe I can find a solution for the first one if the second case works.

I made sure, that Java and VLC are both compiled for Arm64.

Using vlcj on an older Intel x64 Mac or Windows 10 is working without a problem. It is also working when using the Intel x64 JRE and VLC on the Mac with the M1 chip (Rosetta). Starting VLC for Arm64 works fine, too.

I would appreciate any help with this problem. Hopefully it’s just something simple I overlooked.

**Comment by caprica** [comment]
Does JNA provide a native implementation for M1? Presumably it's a brand new CPU architecture. If JNA supports M1, then vlcj will. Perhaps all that is required is a newer version of JNA.

**Comment by caprica** [comment]
Try replacing/overriding the current vlcj JNA dependency with 5.10.0 and report back whether it resolves your issue or not:

```
<dependency>
  <groupId>net.java.dev.jna</groupId>
  <artifactId>jna</artifactId>
  <version>5.10.0</version>
</dependency>
```

I don't yet have access to M1 hardware.

**Comment by caprica** [comment]
Oh, I just now reviewed your original post and see you are already on JNA 5.10.0.

That being said, I don't see how anything can be fixed in vlcj that would be specific to Apple M1 hardware.

**Comment by caprica** [comment]
You could try setting this environment variable explicitly:

```
VLC_PLUGIN_PATH=/Applications/VLC.app/Contents/Frameworks/plugins
```

**Comment by caprica** [comment]
Apart from that suggestion, and based on what you posted, I don't know what else to say.

Acquiring M1 hardware just to troubleshoot this issue is beyond this project at the moment.

**Comment by dramms** [comment]
Hey caprica,

Thank you for answering. I appreciate that you looked into my issue.

As you already noticed, I have updated JNA to 5.10.0. You mentioned this as a possible fix in a different macOS related bug.

I didn’t try setting the VLC_PLUGIN_PATH yet, but will try this next.

I will update this issue in case I can find a solution for my problem.

**Comment by caprica** [comment]
Closing due to lack of activity, if new information comes to light it can be reopened.
