### ISSUE TITLE
Invalid memory access when releasing media player after stream error

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj#1136]
When using vlcj 4.x, check equalizer handling on release.

```
Exception in thread "AWT-EventQueue-0" java.lang.Error: Invalid memory access
        at uk.co.caprica.vlcj.binding.LibVlc.libvlc_media_player_set_equalizer(Native Method)
        at uk.co.caprica.vlcj.player.base.AudioApi.applyEqualizer(AudioApi.java:283)
        at uk.co.caprica.vlcj.player.base.AudioApi.setEqualizer(AudioApi.java:263)
        at uk.co.caprica.vlcj.player.base.AudioApi.release(AudioApi.java:367)
        at uk.co.caprica.vlcj.player.base.MediaPlayer.release(MediaPlayer.java:275)
```

User reported that this occurred after a failing stream, but equalizer seems a strange thing to be implicated just because of a failing stream.

Check also if this issue may be present in vlcj 5.x.

Native code _may_ be implicated here, not sure yet - e.g. is the media player pointer no longer valid?

**Comment by caprica** [comment]
Implicated code in vlcj:
```
274    private void applyEqualizer() {
275        if (equalizerInstance != null) {
276            libvlc_audio_equalizer_set_preamp(equalizerInstance, equalizer.preamp());
277            for(int i = 0; i < libvlc_audio_equalizer_get_band_count(); i ++ ) {
278                libvlc_audio_equalizer_set_amp_at_index(equalizerInstance, equalizer.amp(i), i);
279            }
280          libvlc_media_player_set_equalizer(mediaPlayerInstance, equalizerInstance);
281       }
282        else {
283            libvlc_media_player_set_equalizer(mediaPlayerInstance, null); <---
284        }
285    }
```

So, either:

 1. mediaPlayerInstance is null.
 2. the native method does not like the null parameter for equalizer.
 3. mediaPlayerInstance is a native pointer that is somehow no longer valid (the native side already freed it?).
 4. ?

But, nothing ever sets mediaPlayerInstance to null, thereby ruling out (1).
Setting null for the equalizer instance has definitely worked previously, thereby ruling out (2).
Which leaves (3), or (4).

In principal, during release of the media player we do not need to explicitly unset the equalizer, but it should work regardless. And if that code is removed, it might just push the problem to the next thing that gets released.

**Comment by caprica** [comment]
Can not reproduce.

**Comment by caprica** [comment]
Closing, can be re-opened if more information is provided with a way to reproduce.
