### ISSUE TITLE
MacOS M1 JNA Error 

### ISSUE THREAD

**Issue by BergHeisen** [caprica/vlcj#1145]
Using the library on 4.7.2 causes a error:

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /Users/USER/Library/Caches/JNA/temp/jna8930603134184678173.tmp: dlopen(/Users/USER/Library/Caches/JNA/temp/jna8930603134184678173.tmp, 0x0001): tried: '/Users/USER/Library/Caches/JNA/temp/jna8930603134184678173.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
```
	
Using exactly the same code on Windows works fine, Im pretty sure if I run it on x86_64 it would work, but I do not have the x64 binaries on my M1

Here the repo that I ran on the machine
https://github.com/JetBrains/compose-jb/tree/master/experimental/components

**Comment by BergHeisen** [comment]
So using a non aarch64 jdk and installing VLC meant for Intel + Apple Silicon fixes the problem, using a aarch64 jdk still gives the same issue.

**Comment by caprica** [comment]
Most likely JNA does not support that architecture.

**Comment by caprica** [comment]
Same as #1095 and #1102.

**Comment by BergHeisen** [comment]
#1095 you mention using JNA 5.10.0
```
    implementation("net.java.dev.jna:jna:5.10.0")
    implementation("net.java.dev.jna:jna-platform:5.10.0")
    implementation("uk.co.caprica:vlcj:4.7.2")
```
This is what I have in my build.gradle.kts

**Comment by caprica** [comment]
Yes, at the time that suggestion turned out to be wrong.

Even latest JNA it still does not work as far as I know.

https://search.maven.org/search?q=g:net.java.dev.jna

**Comment by BergHeisen** [comment]
Oh wow, my bad 5.11.0 does actually fix it

Just now there is a different issue, when using runDistribute task

```
May 15, 2022 8:48:53 PM com.sun.jna.Native$1 uncaughtException
WARNING: JNA: Callback uk.co.caprica.vlcj.player.embedded.videosurface.CallbackVideoSurface$SetupCallback@1d633b8f threw the following exception
java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.player.embedded.videosurface.ByteBufferFactory
```
is now being thrown a lot of times, causing the video not to be displayed and audio to be randomly stopping and resuming

**Comment by caprica** [comment]
Good to know that 5.11.0 fixes it. I don't have M1 hardware so I can't test.

If you have a different issue, it should be raised separately.
