### ISSUE TITLE
macos: Native Discovery fails vlcj 5.0.0 and VLC 4 

### ISSUE THREAD

**Issue by tksarul** [caprica/vlcj#1177]
I try to run uk.co.caprica.vlcj.test.direct.DirectTestPlayer example in macos 12.6.1,  but i get below exception.
```
vlcj             : 5.0.0-SNAPSHOT
os               : Mac OS X 12.6.1 x86_64
java             : 17.0.5 Oracle Corporation
java.home        : /Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home
jna.library.path : <not set>
java.library.path: /Applications/VLC.App/Contents/Frameworks:/Users/arul/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
PATH             : /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home/bin:/Users/arul/work/software/apache-maven-3.8.6/bin
VLC_PLUGIN_PATH  : /Applications/VLC.App/Contents/Frameworks/plugins
DYLD_LIBRARY_PATH          : /Applications/VLC.App/Contents/Frameworks
DYLD_FALLBACK_LIBRARY_PATH : <not set>

Error looking up function 'libvlc_media_player_record': dlsym(0x209d0c6c0, libvlc_media_player_record): symbol not found
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.lib.LibVlc
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.tryLoadingLibrary(NativeDiscovery.java:187)
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.discover(NativeDiscovery.java:118)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:176)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at uk.co.caprica.vlcj.test.direct.DirectTestPlayer.<init>(DirectTestPlayer.java:110)
	at uk.co.caprica.vlcj.test.direct.DirectTestPlayer.main(DirectTestPlayer.java:151)

VLC installation path
$ pwd
/Applications/VLC.App/Contents/Frameworks
$ ls -l
total 4088
drwxr-xr-x@   8 arul  admin      256 Jul  3  2022 Sparkle.framework
-rwxr-xr-x@   1 arul  admin   210136 Jul  3  2022 libvlc.12.dylib
lrwxr-xr-x    1 arul  admin       15 Jul  3  2022 libvlc.dylib -> libvlc.12.dylib
-rwxr-xr-x@   1 arul  admin  1877920 Jul  3  2022 libvlccore.9.dylib
lrwxr-xr-x    1 arul  admin       18 Jul  3  2022 libvlccore.dylib -> libvlccore.9.dylib
drwxr-xr-x@   8 arul  admin      256 Jul  3  2022 lua
drwxr-xr-x@ 373 arul  admin    11936 Jul  3  2022 plugins

$  ../MacOS/VLC -version
VLC media player 4.0.0-dev Otto Chriek (revision 4.0.0-dev-19979-g9979f075c9)
 ```

**Comment by caprica** [comment]
>Error looking up function 'libvlc_media_player_record': dlsym(0x209d0c6c0, libvlc_media_player_record): symbol not found

vlcj 5.x uses the bleeding edge pre-release version of VLC 4.x, and this has the libvlc_media_player_record native method.

The version of VLC you are using does not have libvlc_media_player_record native method.

You need a later version of VLC.

**Comment by tksarul** [comment]
Thank You!

I got the latest VLC from https://artifacts.videolan.org/vlc/nightly-macos-x86_64/20230125-0415/. Is it right?

Now I get below error
Connected to the target VM, address: '127.0.0.1:53722', transport: 'socket'
vlcj             : 5.0.0-SNAPSHOT
os               : Mac OS X 12.6.1 x86_64
java             : 17.0.5 Oracle Corporation
java.home        : /Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home
jna.library.path : <not set>
java.library.path: /Applications/VLC.App/Contents/Frameworks:/Users/arul/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
PATH             : /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home/bin:/Users/arul/work/software/apache-maven-3.8.6/bin
VLC_PLUGIN_PATH  : /Applications/VLC.App/Contents/Frameworks/plugins
DYLD_LIBRARY_PATH          : /Applications/VLC.App/Contents/Frameworks
DYLD_FALLBACK_LIBRARY_PATH : <not set>

Error looking up function 'libvlc_audio_get_channel': dlsym(0x20f8d4820, libvlc_audio_get_channel): symbol not found
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.lib.LibVlc
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.tryLoadingLibrary(NativeDiscovery.java:187)
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.discover(NativeDiscovery.java:118)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:176)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at uk.co.caprica.vlcj.test.direct.DirectTestPlayer.<init>(DirectTestPlayer.java:107)
	at uk.co.caprica.vlcj.test.direct.DirectTestPlayer.main(DirectTestPlayer.java:154)

**Comment by caprica** [comment]
Check your own logs and you'll see this:

```
Error looking up function 'libvlc_audio_get_channel': dlsym(0x20f8d4820, libvlc_audio_get_channel): symbol not found
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.lib.LibVlc
```

So there is still a mismatch between vlcj 5.x and VLC.

You also need to build vlcj-5.0.0-SNAPSHOT yourself, the snapshot repo isn't always up to date and there is no formal release of either yet.

**Comment by tksarul** [comment]
Thank you very much. I have build vlcj 5.X and vlcj-natives 5.X locally and It plays my video nicly. WoW I am on VLC 4.X and VLCJ 5.x. Great!

but still i get below error related to Sparkle.framework. Do i need to set any path for Sparkle?
vlcj             : 5.0.0-SNAPSHOT
os               : Mac OS X 12.6.1 x86_64
java             : 17.0.5 Oracle Corporation
java.home        : /Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home
jna.library.path : <not set>
java.library.path: /Users/arul/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
PATH             : /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home/bin:/Users/arul/work/software/apache-maven-3.8.6/bin
VLC_PLUGIN_PATH  : <not set>
DYLD_LIBRARY_PATH          : <not set>
DYLD_FALLBACK_LIBRARY_PATH : <not set>
[00007000032039d8] main generic error: cannot load plug-in /Applications/VLC.app/Contents/Frameworks/plugins/libmacosx_plugin.dylib: dlopen(/Applications/VLC.app/Contents/Frameworks/plugins/libmacosx_plugin.dylib, 0x0001): Library not loaded: '@rpath/Sparkle.framework/Versions/A/Sparkle'
  Referenced from: '/Applications/VLC.app/Contents/Frameworks/plugins/libmacosx_plugin.dylib'
  Reason: tried: '/Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home/bin/./Sparkle.framework/Versions/A/Sparkle' (no such file), '/Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home/bin/../lib/Sparkle.framework/Versions/A/Sparkle' (no such file), '/System/Library/Frameworks/Sparkle.framework/Versions/A/Sparkle' (no such file)

[00007000032038f8] main generic error: cannot load plug-in /Applications/VLC.app/Contents/Frameworks/plugins/libmacosx_plugin.dylib: dlopen(/Applications/VLC.app/Contents/Frameworks/plugins/libmacosx_plugin.dylib, 0x0001): Library not loaded: '@rpath/Sparkle.framework/Versions/A/Sparkle'
  Referenced from: '/Applications/VLC.app/Contents/Frameworks/plugins/libmacosx_plugin.dylib'
  Reason: tried: '/Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home/bin/./Sparkle.framework/Versions/A/Sparkle' (no such file), '/Library/Java/JavaVirtualMachines/jdk-17.0.5.jdk/Contents/Home/bin/../lib/Sparkle.framework/Versions/A/Sparkle' (no such file), '/System/Library/Frameworks/Sparkle.framework/Versions/A/Sparkle' (no such file)
[0000600003070000] window_macosx window: using the macOS new video output window module
[00007f877209e600] videotoolbox decoder: Using Video Toolbox to decode 'h264'

**Comment by caprica** [comment]
No idea, that's nothing to do with vlcj.
