### ISSUE TITLE
VLC 4.0 internal api changes

### ISSUE THREAD

**Issue by acely** [caprica/vlcj#1178]
Noticed after 30-Dec-2022 vlc 4.0 has changed some api, and vlcj will fail to load libvlc.

Java version = 11
VLC version = 4.0.0-dev-intel64-1cc3ce63 (30-Dec-2022 04:13)
System = macOS 11.4
```
Error looking up function 'libvlc_audio_get_channel': dlsym(0x7fb7e7b4e140, libvlc_audio_get_channel): symbol not found
...
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.LibVlc
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.tryLoadingLibrary(NativeDiscovery.java:187)
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.discover(NativeDiscovery.java:118)
```

**Comment by caprica** [comment]
The snapshot versions in the repos are out of date, but if you build the latest from GitHub it will work with the latest VLC 4.x nightly/git.

**Comment by caprica** [comment]
I will try and find some time to push latest snapshots, I can't promise when though.

**Comment by acely** [comment]
Oh yes, the latest git code works fine, thanks!
