### ISSUE TITLE
vlcj 3.0.0 fails to initialize vlc

### ISSUE THREAD

**Issue by krheinwald** [caprica/vlcj#226]
Plain BasicEmbeddedMediaPlayerComponentTest.java with additional NativeDiscovery().discover() at the start.

VLC 2.1.2 installed and found by NativeDiscovery().discover()

Same sample from 2.4.1 works fine. 

Output:

```
jna.library.path: null
java.class.path: C:\Users\krheinwald\Development\ThirdParty\vlcj-3.0.0\jna-4.0.0.jar;C:\Users\krheinwald\Development\ThirdParty\vlcj-3.0.0\jna-platform-4.0.0.jar;C:\Users\krheinwald\Development\NB_Projects\vlcj\build\classes

---
vlcj: (Info.java:70)                                 | INFO  | vlcj: <version not available>
vlcj: (Info.java:71)                                 | INFO  | java: 1.7.0_45 Oracle Corporation
vlcj: (Info.java:72)                                 | INFO  | java home: C:\Program Files (x86)\Java\jdk1.7.0_45\jre
vlcj: (Info.java:73)                                 | INFO  | os: Windows 7 6.1 x86
vlcj: (NativeDiscovery.java:98)                      | DEBUG | discover()
vlcj: (NativeDiscovery.java:101)                     | DEBUG | jnaLibraryPath=null
vlcj: (NativeDiscovery.java:106)                     | DEBUG | discoveryStrategy=uk.co.caprica.vlcj.discovery.linux.DefaultLinuxNativeDiscoveryStrategy@18f1a31
vlcj: (NativeDiscovery.java:109)                     | DEBUG | supported=false
vlcj: (NativeDiscovery.java:106)                     | DEBUG | discoveryStrategy=uk.co.caprica.vlcj.discovery.windows.DefaultWindowsNativeDiscoveryStrategy@c550
vlcj: (NativeDiscovery.java:109)                     | DEBUG | supported=true
vlcj: (AbstractNativeDiscoveryStrategy.java:49)      | DEBUG | discover()
vlcj: (WindowsRuntimeUtil.java:56)                   | DEBUG | getVlcInstallDir()
vlcj: (AbstractNativeDiscoveryStrategy.java:54)      | DEBUG | directoryNames=[., C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\windows\system32, C:\windows, C:\windows\System32\Wbem, C:\windows\System32\WindowsPowerShell\v1.0\, c:\Program Files\WIDCOMM\Bluetooth Software\, c:\Program Files\WIDCOMM\Bluetooth Software\syswow64, C:\Program Files (x86)\Common Files\Roxio Shared\10.0\DLLShared\, C:\Program Files (x86)\Common Files\Teleca Shared, C:\Program Files (x86)\Common Files\Acronis\SnapAPI\, C:\Program Files (x86)\Acronis\TrueImageHome\, C:\Program Files (x86)\QuickTime\QTSystem\, C:\Program Files\Intel\WiFi\bin\, C:\Program Files\Common Files\Intel\WirelessCommon\, C:\Program Files (x86)\GnuPG\pub, C:\Program Files (x86)\Atmel\Flip 3.4.3\bin, C:\Program Files\Intel\WiFi\bin\, C:\Program Files\Common Files\Intel\WirelessCommon\, C:\Program Files (x86)\VideoLAN\VLC]
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=.
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\windows\system32
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\windows
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\windows\System32\Wbem
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\windows\System32\WindowsPowerShell\v1.0\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=c:\Program Files\WIDCOMM\Bluetooth Software\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=c:\Program Files\WIDCOMM\Bluetooth Software\syswow64
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files (x86)\Common Files\Roxio Shared\10.0\DLLShared\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files (x86)\Common Files\Teleca Shared
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files (x86)\Common Files\Acronis\SnapAPI\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files (x86)\Acronis\TrueImageHome\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files (x86)\QuickTime\QTSystem\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files\Intel\WiFi\bin\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files\Common Files\Intel\WirelessCommon\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files (x86)\GnuPG\pub
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files (x86)\Atmel\Flip 3.4.3\bin
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files\Intel\WiFi\bin\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files\Common Files\Intel\WirelessCommon\
vlcj: (AbstractNativeDiscoveryStrategy.java:95)      | DEBUG | Failed to matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:57)      | DEBUG | directoryName=C:\Program Files (x86)\VideoLAN\VLC
vlcj: (AbstractNativeDiscoveryStrategy.java:85)      | DEBUG | Matched 'libvlc.dll' in 'C:\Program Files (x86)\VideoLAN\VLC'
vlcj: (AbstractNativeDiscoveryStrategy.java:85)      | DEBUG | Matched 'libvlccore.dll' in 'C:\Program Files (x86)\VideoLAN\VLC'
vlcj: (AbstractNativeDiscoveryStrategy.java:88)      | DEBUG | Matched all required files
vlcj: (AbstractNativeDiscoveryStrategy.java:63)      | DEBUG | result=C:\Program Files (x86)\VideoLAN\VLC
vlcj: (NativeDiscovery.java:112)                     | DEBUG | path=C:\Program Files (x86)\VideoLAN\VLC
vlcj: (NativeDiscovery.java:114)                     | INFO  | Discovery found libvlc at 'C:\Program Files (x86)\VideoLAN\VLC'
vlcj: (LibVlcFactory.java:164)                       | INFO  | vlc: 2.1.2 Rincewind, changeset 2.1.2-0-ga4c4876
vlcj: (LibVlcFactory.java:165)                       | INFO  | libvlc: C:\Program Files (x86)\VideoLAN\VLC\libvlc.dll
vlcj: (MediaPlayerFactory.java:259)                  | DEBUG | MediaPlayerFactory(libvlc=Proxy interface to Native Library <C:\Program Files (x86)\VideoLAN\VLC\libvlc.dll@1630535680>,libvlcArgs=[--video-title=vlcj video output, --no-snapshot-preview, --quiet, --quiet-synchro, --sub-filter=logo:marq, --intf=dummy])
vlcj: (MediaPlayerFactory.java:261)                  | DEBUG | jna.library.path=null
vlcj: (MediaPlayerFactory.java:275)                  | DEBUG | instance=null
vlcj: (MediaPlayerFactory.java:277)                  | ERROR | Failed to initialise libvlc
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Failed to initialise libvlc.
```

**Comment by Abu-Abdullah** [comment]
the same goes here, with JNA 4, i got the same issue. with 3.5.2 it is working fine.

**Comment by caprica** [comment]
JNA has still not made a new release, it has been almost one year since the last JNA release.

Which documentation are you reading that still says JNA 4?

**Comment by caprica** [comment]
Tracked under #258.

**Comment by Abu-Abdullah** [comment]
this page:
http://caprica.github.io/vlcj/

**Comment by caprica** [comment]
Thanks, it easy to forget to update that page on a different branch when changing the README in the master branch.

**Comment by seannybgoode** [comment]
I'm still getting a plugin error after you guys did the upgrade to JNA 4.1.0.

This is the init code (from the YouTubePlayer.java), slightly modified to point to my vlc dll files:
`public static void main(String[] args) throws Exception {
    	NativeLibrary.addSearchPath("libvlc", "lib/");
        setLookAndFeel();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new YouTubePlayer().start();
            }
        });
    }`

This is my stack trace:

> [00ad9864] core libvlc error: No plugins found! Check your VLC installation.
82 [AWT-EventQueue-0] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - instance=null
82 [AWT-EventQueue-0] ERROR uk.co.caprica.vlcj.player.MediaPlayerFactory  - Failed to initialise libvlc
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Failed to initialise libvlc.

This is most often caused either by an invalid vlc option being passed when creating a MediaPlayerFactory or by libvlc being unable to locate the required plugins.

If libvlc is unable to locate the required plugins the instructions below may help:

In the text below <libvlc-path> represents the name of the directory containing "libvlc.dll" and "libvlccore.dll" and <plugins-path> represents the name of the directory containing the vlc plugins...

For libvlc to function correctly the vlc plugins must be available, there are a number of different ways to achieve this:
 1. Make sure the plugins are installed in the "<libvlc-path>/plugins" directory, this should be the case with a normal vlc installation.
 2. Set the VLC_PLUGIN_PATH operating system environment variable to point to "<plugins-path>".

More information may be available in the log.


	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:300)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:259)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:239)
	at uk.co.caprica.vlcj.test.youtube.YouTubePlayer.<init>(YouTubePlayer.java:150)
	at uk.co.caprica.vlcj.test.youtube.YouTubePlayer$1.run(YouTubePlayer.java:90)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Abu-Abdullah** [comment]
this is solved by JNA 4.2.0

**Comment by betanets** [comment]
For everyone who experiencing same issue on versions 3.0.0, 3.10.0 or 3.10.1:
There is two ways to solve this problem:
1. Upgrade/Downgrade to vlcj 3.9.0 which uses JNA 3.5.2
2. Include latest JNA version into your project and exclude JNA from vlcj, for example, this way:
```xml
<dependency>
    <groupId>uk.co.caprica</groupId>
    <artifactId>vlcj</artifactId>
    <version>3.10.1</version>
    <exclusions>
        <exclusion>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
        </exclusion>
        <exclusion>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>5.0.0</version>
</dependency>
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna-platform</artifactId>
    <version>5.0.0</version>
</dependency>
```
Tested on Windows 10 x64 with VLC 3.0.4 (x64) and Linux Mint 19 x64 with VLC 3.0.3.

**Comment by caprica** [comment]
Interesting that JNA 5.x supposedly mitigates this, but what about #639?
