### ISSUE TITLE
Unable to load library 'libvlc': JNA native support (win32-amd64/libvlc.dll) not found in resource path

### ISSUE THREAD

**Issue by shamun** [caprica/vlcj#359]
I am getting this following error, can you please check what is going wrong?
Jar files are loaded ( from http://capricasoftware.co.uk/downloads/vlcj/vlcj-3.6.0-dist.zip ) and dll files are  also available as below (Windows 8.1 64-bit, VLC 2.2.0 64-bit):

```
C:\Program Files (x86)\VideoLAN\VLC>dir
 Volume in drive C has no label.
 Volume Serial Number is BC82-1133

 Directory of C:\Program Files (x86)\VideoLAN\VLC

21-09-2014  15:30    <DIR>          .
21-09-2014  15:30    <DIR>          ..
27-02-2015  15:20            16.659 AUTHORS.txt
27-02-2015  15:21           857.368 axvlc.dll
27-02-2015  15:21               294 axvlc.dll.manifest
27-02-2015  15:20            18.092 COPYING.txt
16-03-2015  10:43                55 Documentation.url
27-02-2015  15:21           140.568 libvlc.dll
27-02-2015  15:21         2.628.888 libvlccore.dll
16-03-2015  10:42    <DIR>          locale
21-09-2014  15:30    <DIR>          lua
27-02-2015  15:20           153.773 NEWS.txt
16-03-2015  10:43                64 New_Skins.url
27-02-2015  15:21           659.736 npvlc.dll
27-02-2015  15:21               294 npvlc.dll.manifest
16-03-2015  10:43    <DIR>          plugins
27-02-2015  15:20             2.759 README.txt
21-09-2014  15:30    <DIR>          sdk
21-09-2014  15:30    <DIR>          skins
27-02-2015  15:20             5.605 THANKS.txt
16-03-2015  10:43           265.998 uninstall.exe
16-03-2015  10:43                50 VideoLAN Website.url
27-02-2015  15:21           121.112 vlc-cache-gen.exe
27-02-2015  15:21           134.424 vlc.exe
27-02-2015  15:20               825 vlc.exe.manifest
              18 File(s)      5.006.564 bytes
               7 Dir(s)  180.987.625.472 bytes free
```

ERROR:

``` 
run:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'libvlc': JNA native support (win32-amd64/libvlc.dll) not found in resource path (C:\Users\sunuser\Downloads\vlcj-3.6.0-dist\vlcj-3.6.0\jna-3.5.2.jar;C:\Users\sunuser\Downloads\vlcj-3.6.0-dist\vlcj-3.6.0\platform-3.5.2.jar;C:\Users\sunuser\Downloads\vlcj-3.6.0-dist\vlcj-3.6.0\slf4j-api-1.7.10.jar;C:\Users\sunuser\Downloads\vlcj-3.6.0-dist\vlcj-3.6.0\vlcj-3.6.0-javadoc.jar;C:\Users\sunuser\Downloads\vlcj-3.6.0-dist\vlcj-3.6.0\vlcj-3.6.0-sources.jar;C:\Users\sunuser\Downloads\vlcj-3.6.0-dist\vlcj-3.6.0\vlcj-3.6.0.jar;C:\Users\sunuser\Downloads\vlcj-3.6.0-dist\vlcj-3.6.0\vlcj-3.6.0-test-sources.jar;C:\Users\sunuser\Downloads\vlcj-3.6.0-dist\vlcj-3.6.0\vlcj-3.6.0-tests.jar;C:\Users\sunuser\Documents\NetBeansProjects\rtsp\build\classes)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:220)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:322)
	at com.sun.jna.Library$Handler.<init>(Library.java:142)
	at com.sun.jna.Native.loadLibrary(Native.java:387)
	at com.sun.jna.Native.loadLibrary(Native.java:366)
	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:111)
	at rtsp.Rtsp.main(Rtsp.java:20)
Java Result: 1
BUILD SUCCESSFUL (total time: 1 second)
``` 

CODE:

```
package rtsp;

import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import uk.co.caprica.vlcj.binding.LibVlc;

import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface;
//import uk.co.caprica.vlcj.test.VlcjTest;
import uk.co.caprica.vlcj.discovery.NativeDiscovery;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

public class Rtsp  {
  private static final String NATIVE_LIBRARY_SEARCH_PATH = "C:\\Program Files (x86)\\VideoLAN\\VLC";
  
  public static void main(final String[] args) {
    NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), NATIVE_LIBRARY_SEARCH_PATH);
    //Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
    System.out.println(LibVlc.INSTANCE.libvlc_get_version());
  }
}
```

**Comment by caprica** [comment]
Did you go through this: http://capricasoftware.co.uk/#/projects/vlcj/tutorial/first-steps

**Comment by shamun** [comment]
@caprica : YES i tried first the Option 1 - Automatic Native Discovery and that also failed then i tried the  Option 2 - Explicit Library Path which is still failing. Any idea? (more then 1 year ago i was using old version for Linux i had no problem, but now i need to use one project with vlcj for Windows 8.1)

**Comment by shamun** [comment]
@caprica:  Thank you. my mistake was using VLC 32-bit after remove and reinstall fixed it:
http://download.videolan.org/pub/videolan/vlc/last/win64/vlc-2.2.0-win64.exe
