### ISSUE TITLE
instance always null with JNA 4.x

### ISSUE THREAD

**Issue by LeovR** [caprica/vlcj#446]
Since the upgrade of JNA to version 4.x the instance is always `null`.

I can reconstruct the error with the quickstart/Example2 test class.

The console output is as follows:
```
[000000000088d260] core libvlc error: No plugins found! Check your VLC installation.
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Failed to initialise libvlc.

This is most often caused either by an invalid vlc option being passed when creating a MediaPlayerFactory or by libvlc being unable to locate the required plugins.

If libvlc is unable to locate the required plugins the instructions below may help:

In the text below <libvlc-path> represents the name of the directory containing "libvlc.dll" and "libvlccore.dll" and <plugins-path> represents the name of the directory containing the vlc plugins...

For libvlc to function correctly the vlc plugins must be available, there are a number of different ways to achieve this:
 1. Make sure the plugins are installed in the "<libvlc-path>/plugins" directory, this should be the case with a normal vlc installation.
 2. Set the VLC_PLUGIN_PATH operating system environment variable to point to "<plugins-path>".

More information may be available in the log.


	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:300)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:259)
	at uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent.onGetMediaPlayerFactory(EmbeddedMediaPlayerComponent.java:349)
	at uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent.<init>(EmbeddedMediaPlayerComponent.java:217)
	at uk.co.caprica.vlcj.test.quickstart.Example2.<init>(Example2.java:52)
	at uk.co.caprica.vlcj.test.quickstart.Example2$1.run(Example2.java:46)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I am using Windows 10 and JDK 1.8.0_60.

If I reverse f53f8627d3c6f8091f46140f60008d4604c25b2c everything is working fine.

**Comment by caprica** [comment]
Specifically which version of JNA are you using?

I tested this was OK on Windows with JNA 4.1.0, which is the version in the vlcj pom.xml.

**Comment by LeovR** [comment]
This happens with vlcj 3.10.0 => JNA version 4.1.0

**Comment by caprica** [comment]
It works for me on Windows if I set the VLC_PLUGIN_PATH environment variable.

It's a pain, but this piece of vlcj code is wholly reliant on the JNA implementation. vlcj can't stay on JNA 3.x forever.

**Comment by LeovR** [comment]
It is working with the environment variable set.
I was just wondering why it was working with JNA 3.x without setting anything.

**Comment by caprica** [comment]
Me too...

**Comment by caprica** [comment]
I tried a workaround in #449.

It will be in the next release of vlcj, whenever that time comes...
