### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by marianpavel** [caprica/vlcj#474]
I have updated from vlcj 3.9 to 3.10 and I am getting the following error:

Exception in thread "JavaFX Application Thread" java.lang.Error: The system cannot find the path specified.

on this line:

AudioMediaPlayerComponent mediaPlayerComponent = new AudioMediaPlayerComponent();

I was trying to implement JavaSoundTest and I found this error, however after reverting to my default mediaPlayerComponent I found that the error still persisted and it is from the update.

**Comment by caprica** [comment]
Insufficient information to help you.

**Comment by marinica94** [comment]
Doing a simple update of the library from 3.9.0 to 3.10.1 gave me the following error:

`Exception in thread "JavaFX Application Thread" java.lang.Error: The system cannot find the path specified.

	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:171)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:115)
	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:165)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:259)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:177)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:109)
	at Player.start(Player.java:191)
	at Main.lambda$null$1(Main.java:146)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)`

I am creating the AudioMediaPlayerComponent and initializing it in the method:

`private AudioMediaPlayerComponent mediaPlayerComponent;

mediaPlayerComponent = new AudioMediaPlayerComponent();`

**Comment by caprica** [comment]
Some problem with JNA then.

I probably will revert JNA in vlcj back to 3.5.2 because I am thoroughly
sick of the problems JNA 4 has brought.
