### ISSUE TITLE
Video freezes and IllegalArgumentException is thrown

### ISSUE THREAD

**Issue by markusbrovold** [caprica/vlcj#491]
Hi,

Java version: 1.8.0_73-b02, build 25.73-b02

After I start streaming a live-feed, everything freezes and I get this stacktrace:

`[15df4b04] ts demux: MPEG-4 descriptor not found for pid 0x101 type 0xf
[1ba3e764] packetizer_mpeg4audio packetizer: AAC channels: 2 samplerate: 24000
[1b9e9cdc] core vout display error: Failed to change zoom
[1b9e9cdc] core vout display error: Failed to set on top
[1b9e9cdc] core vout display error: Failed to change source AR
[15df4b04] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
[15df4b04] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
[15df4b04] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
[15df4b04] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
[15df4b04] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
java.lang.IllegalArgumentException: Upload requires 8294400 elements, but only 6942720 elements remain in the buffer
	at com.sun.prism.impl.BaseTexture.checkUpdateParams(Unknown Source)
	at com.sun.prism.d3d.D3DTexture.update(Unknown Source)
	at com.sun.prism.impl.BaseTexture.update(Unknown Source)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(Unknown Source)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(Unknown Source)
	at com.sun.javafx.sg.prism.NGImageView.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGImageView.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(Unknown Source)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(Unknown Source)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at com.sun.javafx.tk.RenderJob.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[15df4b04] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
[15df4b04] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
[15df4b04] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095
java.lang.IllegalArgumentException: Upload requires 8294400 elements, but only 7557120 elements remain in the buffer
	at com.sun.prism.impl.BaseTexture.checkUpdateParams(Unknown Source)
	at com.sun.prism.d3d.D3DTexture.update(Unknown Source)
	at com.sun.prism.impl.BaseTexture.update(Unknown Source)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(Unknown Source)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(Unknown Source)
`

**Comment by caprica** [comment]
So it looks like you got a corrupted or incomplete video frame and it failed when you tried to draw the frame.

Probably all you can do is catch the exception and try and continue. Hopefully the next frame will eventually recover. Point is, stuff like this can't really be "fixed" in vlcj.

**Comment by markusbrovold** [comment]
Ok. Any suggestion on where to catch the exception?

**Comment by caprica** [comment]
Oh, I see it's deep in JavaFX code and not your application code. I don't know...

**Comment by caprica** [comment]
The point here is that the buffer you sent to JavaFX was not valid. So you need to detect that, somehow, at the point you make the JavaFX API call to update the image.
