### ISSUE TITLE
vlcj crashes when trying to load VLC from a Windows shared drive

### ISSUE THREAD

**Issue by xinyingho** [caprica/vlcj#493]
I'm on Windows7 64-bit / Java 64-bit 1.8.0.92 / VLC 64-bit 2.2.3.
I have a Java application and a portable version of VLC both installed on the same Windows shared drive. So both must be accessed from UNC-styled paths, e.g. "\\\\\<drive>\\\<folder>"
My application overrides the constructor of NativeDiscovery to provide a subclass of DefaultWindowsNativeDiscoveryStrategy, which add into directoryNames of onGetDirectoryNames(List<String> directoryNames) the relative path of VLC from my Java app, e.g. "vlc2.2.3\App\VLCMediaPlayer\libvlc.dll".
When launching my Java app from a local drive, everything's fine. When doing the same from a Windows shared drive, VLCj raises a java.lang.Error throwable telling that some paths aren't valid. It seems like it's because JNA 4.1.0 can't manage Windows shared drives as the exception is raised at this line of the DefaultWindowsNativeDiscoveryStrategy class:

    public void onFound(String path) {
        if (LibVlcVersion.getVersion().atLeast(LibVlcVersion.LIBVLC_220)) {

I don't know if there's a newer version of JNA that fixed this?

**Comment by caprica** [comment]
Please post the full stack trace.

JNA 4.x has caused severe problems with loading LibVLC and its plugins, if anything I'd recommend going *backwards* to 3.5.x rather than forwards to a new version of JNA.

**Comment by xinyingho** [comment]
Here's the stack trace (the error can be translated from French to English as "the syntax of the filename, of the directory or of the drive is incorrect"):

java.lang.Error: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.

	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:171)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:115)
	at uk.co.caprica.vlcj.version.LibVlcVersion.<clinit>(LibVlcVersion.java:32)
	at uk.co.caprica.vlcj.discovery.windows.DefaultWindowsNativeDiscoveryStrategy.onFound(DefaultWindowsNativeDiscoveryStrategy.java:71)
	at uk.co.caprica.vlcj.discovery.NativeDiscovery.discover(NativeDiscovery.java:125)
	at net.babelsoft.negatron.io.Video.isEnabled(Video.java:46)
	at net.babelsoft.negatron.view.control.MediaViewPane2.<init>(MediaViewPane2.java:162)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at sun.reflect.misc.ReflectUtil.newInstance(Unknown Source)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at net.babelsoft.negatron.view.control.SoftwareInformationPane.<init>(SoftwareInformationPane.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at sun.reflect.misc.ReflectUtil.newInstance(Unknown Source)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at net.babelsoft.negatron.NegatronApp.start(NegatronApp.java:76)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

**Comment by caprica** [comment]
I'm not sure, maybe ask at the JNA project since this does not seem specific to vlcj/LibVLC.

**Comment by xinyingho** [comment]
Sure, will do

**Comment by matthiasblaesing** [comment]
java-native-access/jna#666 was closed - current stable (4.2.2) and my current development version both fix this issue.

**Comment by xinyingho** [comment]
I confirm that upgrading JNA to 4.2.2 fixes this issue.

**Comment by caprica** [comment]
Thanks for the report and the confirmation. I might as well bump a point release for vlcj to pick up the new JNA dependency. It might hopefully fix some of the other annoyances introduced by JNA 4.x.

I'll do that soon-ish.

**Comment by caprica** [comment]
Why did you need to remove MONITORINFO from vlcj? It's in a different package surely?

**Comment by xinyingho** [comment]
JNA now has its own MONITORINFO class. Just change the depency to JNA and recompile VLCj, you'll understand right away.
