### ISSUE TITLE
Recover video after crash 

### ISSUE THREAD

**Issue by jmanuel1609** [caprica/vlcj#505]
Hi:
How can i recover the video after crash. I have this function that is calling in Error event. 

```
public boolean recover(long time) {
		
		mediaPlayerComponent.getMediaPlayer().stop();
		mediaPlayerComponent.getMediaPlayer().release();
		
		String url = this.sharedActions.recoverUrl();
		//System.out.println("Url to recover: " + url);
		mediaPlayerComponent.getMediaPlayer().prepareMedia(url);
		
		recoverTime =  new Long(time);
		return mediaPlayerComponent.getMediaPlayer().start();
		
	}
```

but i have this exception i this line code:
`	mediaPlayerComponent.getMediaPlayer().prepareMedia(url);`
```

java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:367)
	at com.sun.jna.Function.invoke(Function.java:315)
	at com.sun.jna.Library$Handler.invoke(Library.java:212)
	at com.sun.proxy.$Proxy1.libvlc_event_detach(Unknown Source)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.deregisterMediaEventListener(DefaultMediaPlayer.java:2021)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.setMedia(DefaultMediaPlayer.java:2077)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.prepareMedia(DefaultMediaPlayer.java:282)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.prepareMedia(DefaultMediaPlayer.java:276)
	at com.mediavu.client.player.capricaPlayer.MediavuPlayer.recover(MediavuPlayer.java:256)
	at com.mediavu.client.player.capricaPlayer.view.JPanelVideoContainer.recoverInTime(JPanelVideoContainer.java:406)
	at com.mediavu.client.player.capricaPlayer.view.JPanelVideoContainer.access$10(JPanelVideoContainer.java:391)
	at com.mediavu.client.player.capricaPlayer.view.JPanelVideoContainer$5.run(JPanelVideoContainer.java:440)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
thanks in advance

**Comment by caprica** [comment]
You can't use a media player instance after you released it.

As for the particular error, I'm not sure, but behaviour is "undefined" if you try and use a media player after releasing it.

**Comment by jmanuel1609** [comment]
yes you are right i remove  mediaPlayerComponent.getMediaPlayer().release(); and then i can recover..
are there some event when the the media was released?
