### ISSUE TITLE
Direct Rendering fails on Mac OS X 10.13.3 (High Sierra), java 1.8

### ISSUE THREAD

**Issue by tfonrouge** [caprica/vlcj#595]
Running the example of Direct Rendering at (http://capricasoftware.co.uk/#/projects/vlcj/tutorial/direct-rendering) fails with the following error:

objc[11709]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java (0x10e2cb4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10e3574e0). One of the two will be used. Which one is undefined.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[00007f85cb854920] videotoolbox decoder: Using Video Toolbox to decode 'h264'
[00007f85c9ff9f00] main audio output error: too low audio sample frequency (0)
[00007f85cf77a380] main decoder error: failed to create audio output
[00007f85c9ff9f00] auhal audio output error: opening auhal output failed
[00007f85c9ff9f00] main audio output error: module not functional
JNA: Callback uk.co.caprica.vlcj.player.DefaultMediaPlayer$EventCallback@74d45940 threw the following exception:
java.lang.IllegalArgumentException: No field of type class uk.co.caprica.vlcj.binding.internal.media_player_chapter_changed in libvlc_event_u(native@0x700007541ce0) (16 bytes) {
  media_meta_changed media_meta_changed@0=media_meta_changed(auto-allocated@0x7f85c9e37160 (4 bytes)) {
    int meta_type@0=0
  }
  media_subitem_added media_subitem_added@0=media_subitem_added(auto-allocated@0x7f85c9e22370 (8 bytes)) {
    libvlc_media_t new_child@0=NULL
  }
  media_duration_changed media_duration_changed@0=media_duration_changed(auto-allocated@0x7f85c9e15fb0 (8 bytes)) {
    long new_duration@0=0
  }
  media_parsed_changed media_parsed_changed@0=media_parsed_changed(auto-allocated@0x7f85c9e20a10 (4 bytes)) {
    int new_status@0=0
  }
  media_freed media_freed@0=media_freed(auto-allocated@0x7f85c9e20060 (8 bytes)) {
    libvlc_media_t md@0=NULL
  }
  media_state_changed media_state_changed@0=media_state_changed(auto-allocated@0x7f85c9e200b0 (4 bytes)) {
    int new_state@0=0
  }
  media_player_buffering media_player_buffering@0=media_player_buffering(auto-allocated@0x7f85c9e158a0 (4 bytes)) {
    float new_cache@0=0.0
  }
  media_player_position_changed media_player_position_changed@0=media_player_position_changed(auto-allocated@0x7f85c9e1f370 (4 bytes)) {
    float new_position@0=0.0
  }
  media_player_time_changed media_player_time_changed@0=media_player_time_changed(auto-allocated@0x7f85c9e1da50 (8 bytes)) {
    long new_time@0=0
  }
  media_player_title_changed media_player_title_changed@0=media_player_title_changed(auto-allocated@0x7f85c9e19860 (4 bytes)) {
    int new_title@0=0
  }
  media_player_seekable_changed media_player_seekable_changed@0=media_player_seekable_changed(auto-allocated@0x7f85c9e16370 (4 bytes)) {
    int new_seekable@0=0
  }
  media_player_pausable_changed media_player_pausable_changed@0=media_player_pausable_changed(auto-allocated@0x7f85c9e01aa0 (4 bytes)) {
    int new_pausable@0=0
  }
  media_player_vout media_player_vout@0=media_player_vout(auto-allocated@0x7f85c9e18480 (4 bytes)) {
    int new_count@0=0
  }
  media_list_item_added media_list_item_added@0=media_list_item_added(auto-allocated@0x7f85c9e1b690 (16 bytes)) {
    libvlc_media_t item@0=NULL
    int index@8=0
  }
  media_list_will_add_item media_list_will_add_item@0=media_list_will_add_item(auto-allocated@0x7f85c9e190e0 (16 bytes)) {
    libvlc_media_t item@0=NULL
    int index@8=0
  }
  media_list_item_deleted media_list_item_deleted@0=media_list_item_deleted(auto-allocated@0x7f85c9e187f0 (16 bytes)) {
    libvlc_media_t item@0=NULL
    int index@8=0
  }
  media_list_will_delete_item media_list_will_delete_item@0=media_list_will_delete_item(auto-allocated@0x7f85c9e18b90 (16 bytes)) {
    libvlc_media_t item@0=NULL
    int index@8=0
  }
  media_list_player_next_item_set media_list_player_next_item_set@0=media_list_player_next_item_set(auto-allocated@0x7f85c9e18970 (8 bytes)) {
    libvlc_media_t item@0=NULL
  }
  media_player_snapshot_taken media_player_snapshot_taken@0=media_player_snapshot_taken(auto-allocated@0x7f85c9e163b0 (8 bytes)) {
    String filename@0=null
  }
  media_player_length_changed media_player_length_changed@0=media_player_length_changed(auto-allocated@0x7f85c9e227e0 (8 bytes)) {
    long new_length@0=0
  }
  vlm_media_event vlm_media_event@0=vlm_media_event(auto-allocated@0x7f85c9e227f0 (16 bytes)) {
    String psz_media_name@0=null
    String psz_instance_name@8=null
  }
  media_player_media_changed media_player_media_changed@0=media_player_media_changed(auto-allocated@0x7f85c9e22800 (8 bytes)) {
    libvlc_media_t md@0=NULL
  }
  media_player_scrambled_changed media_player_scrambled_changed@0=media_player_scrambled_changed(auto-allocated@0x7f85c9e22810 (4 bytes)) {
    int new_scrambled@0=0
  }
  media_player_es_changed media_player_es_changed@0=media_player_es_changed(auto-allocated@0x7f85c9e22820 (8 bytes)) {
    int i_type@0=0
    int i_id@4=0
  }
  media_subitemtree_added media_subitemtree_added@0=media_subitemtree_added(auto-allocated@0x7f85c9e31e10 (8 bytes)) {
    libvlc_media_t item@0=NULL
  }
  media_player_audio_volume media_player_audio_volume@0=media_player_audio_volume(auto-allocated@0x7f85c9e31e20 (4 bytes)) {
    float volume@0=0.0
  }
  media_player_audio_device media_player_audio_device@0=media_player_audio_device(auto-allocated@0x7f85c9e31e30 (8 bytes)) {
    String device@0=null
  }
}
	at com.sun.jna.Union.getTypedValue(Union.java:154)
	at uk.co.caprica.vlcj.player.events.MediaPlayerEventFactory.createEvent(MediaPlayerEventFactory.java:263)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer$EventCallback.callback(DefaultMediaPlayer.java:2216)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:470)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:500)
[00007f85cf77a380] main decoder error: failed to create audio output
[00007f85cb854920] main decoder error: buffer deadlock prevented
[00007f85cb854920] videotoolbox decoder: vt cvpx chroma: BGRA

**Comment by caprica** [comment]
What version of LibVLC, what version of vlcj? Are you sure your classpath is correct?

**Comment by tfonrouge** [comment]
In my IntelliJ IDEA env, I'm setting environmental variable as follow:

DYLD_LIBRARY_PATH=/Applications/VLC.app/Contents/MacOS/lib

I'm using VLC 3.0.0

May be I need another setup in my environment ?

**Comment by tfonrouge** [comment]
I'm going to close the issue, because I finally managed to compile / run the vlcj-player on Mac OS X, so direct rendering is indeed working on my computer with java 1.8, sorry for the noise

**Comment by tfonrouge** [comment]
Well, the main screen of the vlci-player opens but when I try to play a video shows error on Eclipse IDE:

2018-02-20 20:57:55 INFO                            Info:77   - vlcj: 3.10.1
2018-02-20 20:57:55 INFO                            Info:78   - java: 1.8.0_111 Oracle Corporation
2018-02-20 20:57:55 INFO                            Info:79   - java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre
2018-02-20 20:57:55 INFO                            Info:80   - os: Mac OS X 10.13.3 x86_64
2018-02-20 20:57:55 INFO                 NativeDiscovery:121  - Discovery found libvlc at '/Applications/VLC.app/Contents/MacOS/lib'
2018-02-20 20:57:55 INFO                   LibVlcFactory:171  - vlc: 3.0.0 Vetinari, changeset 3.0.0-3-g7821ebf808
2018-02-20 20:57:55 INFO                   LibVlcFactory:172  - libvlc: /Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Can't load JAWT
	at com.sun.jna.Native.getWindowHandle0(Native Method)
	at com.sun.jna.Native$AWT.getComponentID(Native.java:1973)
	at com.sun.jna.Native.getComponentID(Native.java:265)
	at uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface.attach(CanvasVideoSurface.java:76)
	at uk.co.caprica.vlcj.player.embedded.DefaultEmbeddedMediaPlayer.attachVideoSurface(DefaultEmbeddedMediaPlayer.java:162)
	at uk.co.caprica.vlcj.player.embedded.DefaultEmbeddedMediaPlayer.onBeforePlay(DefaultEmbeddedMediaPlayer.java:327)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.play(DefaultMediaPlayer.java:804)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.playMedia(DefaultMediaPlayer.java:265)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.playMedia(DefaultMediaPlayer.java:256)
	at uk.co.caprica.vlcjplayer.view.main.RecentMediaMenu$PlayRecentAction.actionPerformed(RecentMediaMenu.java:70)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by caprica** [comment]
That is unrelated to your original issue.

It is also already documented https://github.com/caprica/vlcj/search?q=JAWT_GetAWT&type=Issues

e.g. #205
