### ISSUE TITLE
NoSuchFieldError: SIZE_T_SIZE when trying to play from a Stream

### ISSUE THREAD

**Issue by AndreasSchaek** [caprica/vlcj#635]
VLC: 3.0.4 64 bit
VLCJ: 3.10.1

When I try to play Media from any InputStream (let it be FileinputStreamMedia) I get an exception.

`mediaPlayer.playMedia(new FileInputStreamMedia(f))`

results in

`Exception in thread "AWT-EventQueue-0" java.lang.NoSuchFieldError: SIZE_T_SIZE
	at uk.co.caprica.vlcj.binding.support.size_t.<init>(size_t.java:36)
	at uk.co.caprica.vlcj.binding.support.size_t.<init>(size_t.java:32)`

**Comment by AndreasSchaek** [comment]
Version conflict. Had an old jna still in my classpath
