### ISSUE TITLE
Support for VLC 3.0.4 on Mac (Mojave and High Sierra)

### ISSUE THREAD

**Issue by parg** [caprica/vlcj#643]
Hi,
We've had the option to use VLC via vlcj in our media player within Vuze (and now BiglyBT) for sometime - everything was working, or at least we weren't getting any bug reports. However today a user pointed out that it has stopped working on OSX High Sierra (and through some of my testing also Mojave). 

Before I dig into things further, is it known that vlcj_3.10.1 supports VLC 3.0.4 on recent OSX versions? I did try jna 4.5.2 but that didn't help.

Many thanks,
Parg

**Comment by caprica** [comment]
You need to be more specific, but I can say I have not personally tested vlcj with VLC 3.x on OSX.

OSX is an inferior platform for vlcj due to the lack of heavyweight AWT in modern JVM's on OSX.

**Comment by parg** [comment]
I'll try and resurrect an OSX dev env and get back with further info - thanks

**Comment by parg** [comment]
It is failing on discoveryStrategy.onFound( path ) in NativeDiscovery.java with a 

java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.version.LibVlcVersion

after finding the vlc dylib in the usual place (Contents/MacOS/lib)

**Comment by caprica** [comment]
Most likely for an error like that there was some exception thrown during static initialisation somewhere.

**Comment by parg** [comment]
java.lang.UnsatisfiedLinkError: dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib, 9): Library not loaded: @rpath/libvlccore.dylib
  Referenced from: /Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib
  Reason: image not found

**Comment by parg** [comment]
So I don't know how @rpath is supposed to be specified to cause the search for libvlccore.dylib to occur in the right place but I did get things working by explicitly loading libvlccore before libvlc

**Comment by caprica** [comment]
So that's not even a vlcj problem, the same thing will happen if you use JNA directly without vlcj to try and load LibVLC. See #602 and #555 and problably others.

**Comment by parg** [comment]
Here's the code I ended up with in NativeDiscovery::discover():

                   if(path != null) {
                        logger.info("Discovery found libvlc at '{}'", path);
                        // Register the discovered library path with JNA                      
                        String name = RuntimeUtil.getLibVlcLibraryName();
                        
                        // Hack due to https://github.com/caprica/vlcj/issues/643
                        if ( RuntimeUtil.isMac()){
	                        	try{
			                      NativeLibrary.addSearchPath(name+"core", path);
			                      Map<String,?> options = new HashMap<>();
			                      NativeLibrary.getInstance(name+"core", options );
	                        	}catch( Throwable e ){
	                        		e.printStackTrace();
	                        	}
                        }
                        
                        NativeLibrary.addSearchPath(name, path);
                        // Chance for post processing
                        discoveryStrategy.onFound(path);
                        return true;
                    }

Not elegant but might help others - thanks for your help!

**Comment by Abu-Abdullah** [comment]
Hi @caprica 

I'm facing the same issue here with the latest versions of vlcj/vlc
```
Caused by: java.lang.UnsatisfiedLinkError: dlopen(/Users/oracle/Desktop/myapp.app/Contents/Java/resources/bin/vlc/Contents/MacOS/lib/libvlc.dylib, 9): Library not loaded: @rpath/libvlccore.dylib
  Referenced from: /Users/oracle/Desktop/myapp.app/Contents/Java/resources/bin/vlc/Contents/MacOS/lib/libvlc.5.dylib
  Reason: image not found
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:278)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Native.register(Native.java:1722)
	at com.sun.jna.Native.register(Native.java:1443)
	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:98)
	at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:195)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:181)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at com.myapp.JVLC.<init>(JVLC.java:517)
	at com.myapp.AudioCataloger.start(AudioCataloger.java:451)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

I'm just using this code
```
ClassLoader cl = VLC.class.getClassLoader();
NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), new File(cl.getResource("bin/vlc/Contents/MacOS/lib").toURI()).getAbsolutePath());
```
Not really sure what is happing. the classpath contains as well all the locations e.g. resources, MacOS, lib ... etc

**Comment by caprica** [comment]
When I run my vlcj projects, on any platform (Linux, macOS or Windows) I simply create a new MediaPlayerFactory (or one of the Component classes) and it *just works*.

I don't mess around with native library search paths or anything.

If VLC is installed in a non-standard location, I use the ServiceLoader mechanism to load a bespoke instance of a DIscoveryDirectoryProvider.

To reiterate: last time I tested all three platforms, it just worked.

Make sure you install an official VLC package via the normal OS package manager.

**Comment by Abu-Abdullah** [comment]
i  got the same issue as well when installing the play in the default folder from the official vlc site. im focusing to bundle the vlc with the app. i will dig more into this and check other threads.
```
Caused by: java.lang.RuntimeException: Failed to get a new native library instance
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.newLibVlcInstance(MediaPlayerFactory.java:214)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:110)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
```

im testing on mac 10.15.3 with vlc 3.0.10 and latest vlcj

**Comment by caprica** [comment]
When I run vlcj projects on macOS, I first install the official VLC package.

I then do this in code...

```
EmbeddedMediaPlayerComponent mpc = new EmbeddedMediaPlayerComponent();
```

...or I create a MediaPlayerFactory and create what I need from there.

That's it, as far as I remember.

Granted, I don't test on macOS every day, but the last time I tested this it worked.

So I don't know what else I can add.

I will try and find some time to do another test today to confirm.

**Comment by Abu-Abdullah** [comment]
I'm not sure if this issue is related only to Catalina as it seems App Notarization is a must. the access migth be restricted here. i will update later on this part.

**Comment by caprica** [comment]
I just tested this on macOS.

```
vlcj             : 4.4.4
os               : Mac OS X 10.14.6 x86_64
java             : 14 AdoptOpenJDK
java.home        : /Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home
jna.library.path : <not set>
java.library.path: /Users/mark/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
PATH             : /usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
VLC_PLUGIN_PATH  : <not set>
DYLD_LIBRARY_PATH          : <not set>
DYLD_FALLBACK_LIBRARY_PATH : <not set>
```

What you see above is a totally standard installation of Java on macOS, nothing special.

I installed VLC via the standard package installation method, again nothing special.

I then run the JavaFX demo application for vlcj. I do not set any environment variables, I don't enable any special permissions/settings/whatever.

The demo application Java code simply relies on the default NativeDiscovery mechanism that is completely transparent to you as a developer using vlcj.

And it just works perfectly.

**Comment by Abu-Abdullah** [comment]
thank you @caprica for your support. i would really appreciate if you can provide simple example (or a link) on how to add a non standard path using ServiceLoader. previously i was using:
```
NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), path);
```
but this seems not working any more.

**Comment by caprica** [comment]
Well, first question would be why do you need a non-standard path?

But since apparently you do, start here: https://caprica.github.io/vlcj/javadoc/4.4.4/uk/co/caprica/vlcj/factory/discovery/provider/DirectoryProviderDiscoveryStrategy.html

Then look in the vlcj sources for implementations of DiscoveryDirectoryProvider, it's very simple.

For ServiceLoader to find your new class, you need to register it in the META-INF/services directory (usually "src/main/resourcesMETA-INF/services/uk.co.caprica.vlcj.factory.discovery.provider.DiscoveryDirectoryProvider") as per the Javadoc linked above.

Instead of doing that, in 4.4.3+ of vlcj there is a new ConfigurationFileDiscoveryDirectoryProvider class that will read the directory from a ${user.home}/.config/vlcj/vlcj.config file containing a "nativeDirectory" property. However it still may be better for you to write your own implementation that works exactly how you want it to work, they're very simple to write.

Your own implementation could hard-code a path, or read the location from your own application configuration file, or whatever you want.
