### ISSUE TITLE
HeadlessException in springboot project

### ISSUE THREAD

**Issue by VanMesure** [caprica/vlcj#838]
I want to build a server for picture processing, and I use vlcj3 for extracting the frame from rtsp source(or rtmp source), I just want to get the data of the  frame , I do not need to show these frame.  I reference http://capricasoftware.co.uk/projects/vlcj-3/tutorials/direct-rendering to build my project, but wen I  call
`    new NativeDiscovery().discover();
        image = GraphicsEnvironment
                .getLocalGraphicsEnvironment()
                .getDefaultScreenDevice()
                .getDefaultConfiguration()
                .createCompatibleImage(MEDIA_WIDTH, MEDIA_HEIGHT);`
it throws a Exception from the  getDefaultScreenDevice() method:
`java.awt.HeadlessException
	at sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(HeadlessGraphicsEnvironment.java:77)
	at com.qutsmart.core.VLCJCamera.init(VLCJCamera.java:84)
	at com.qutsmart.core.VLCJCamera.start(VLCJCamera.java:107)
	at com.qutsmart.core.FaceDetector.addCaemra(FaceDetector.java:71)
	at com.qutsmart.fore.FaceController.add(FaceController.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
`
How can I solve this problem please?   Thank u very much(●'◡'●)！

**Comment by caprica** [comment]
This issue is really nothing to do with vlcj.

See https://www.oracle.com/technetwork/articles/javase/headless-136834.html
