### ISSUE TITLE
audio tutorial: stopped() called upon play (and hangs on exit)

### ISSUE THREAD

**Issue by wolfgangasdf** [caprica/vlcj#865]
Using vlcj 4.1.0 & vlc 3.0.6, the [audio player tutorial](http://capricasoftware.co.uk/projects/vlcj-4/tutorials/basic-audio-player) doesn't work here (mac) because stopped() is called upon play(), and there it exits (stack trace below). Would it be good to remove the stopped() listener from the tutorial code since the behaviour seems to be intended (player.base.SubitemApi.changeMedia)? 

Another small issue here is that the program hangs on `mediaPlayerComponent.release();` (also if called from finished()), changing to `mediaPlayerComponent.mediaPlayer().submit(mediaPlayerComponent::release);` helps.
Otherwise, it works nicely! 

	at tutorialjava.BasicAudioPlayer$1.stopped(BasicAudioPlayer.java:27)
	at uk.co.caprica.vlcj.player.base.events.MediaPlayerStoppedEvent.notify(MediaPlayerStoppedEvent.java:36)
	at uk.co.caprica.vlcj.player.base.events.MediaPlayerStoppedEvent.notify(MediaPlayerStoppedEvent.java:28)
	at uk.co.caprica.vlcj.support.eventmanager.NativeEventManager.raiseEvent(NativeEventManager.java:179)
	at uk.co.caprica.vlcj.support.eventmanager.NativeEventManager$EventCallback.callback(NativeEventManager.java:206)
	at uk.co.caprica.vlcj.binding.LibVlc.libvlc_media_list_player_stop(Native Method)
	at uk.co.caprica.vlcj.player.list.ControlsApi.stop(ControlsApi.java:72)
	at uk.co.caprica.vlcj.player.base.SubitemApi.changeMedia(SubitemApi.java:106)
	at uk.co.caprica.vlcj.player.base.MediaApi.applyMedia(MediaApi.java:350)
	at uk.co.caprica.vlcj.player.base.MediaApi.changeMedia(MediaApi.java:330)
	at uk.co.caprica.vlcj.player.base.MediaApi.prepare(MediaApi.java:82)
	at uk.co.caprica.vlcj.player.base.MediaApi.play(MediaApi.java:93)
	at tutorialjava.BasicAudioPlayer.start(BasicAudioPlayer.java:45)
	at tutorialjava.BasicAudioPlayer.main(BasicAudioPlayer.java:13)

**Comment by caprica** [comment]
Wow... thanks for the report.

This happened as an unintended consequence of trying to improve sub-item handling in vlcj-4. Sub-item handling is undoubtedly much better now in vlcj-4 compared with previous versions but this problem slipped through the cracks.

And yes, you're absolutely right about release() hanging there too - it is supposed to be well known that it is not allowed to call back into LibVLC from an event thread and that's exactly what this example does. Again, that is something that would have worked with vlcj-3, but not vlcj-4 where the native event threading was changed.

Sadly there are just too many examples now for me to test each one for each release.

**Comment by caprica** [comment]
This is a bug in the example, not vlcj itself.

**Comment by caprica** [comment]
Changes:
d2306c044d9694256a92029d152d05a6536f57cb
f8ad5786a5ac9cf5e298a3d450c64e9734ebf63d

Web-site also changed to fix the tutorial - this will be included in the next web-site build and deployment some time in the coming week.

**Comment by wolfgangasdf** [comment]
Hi, thanks a lot, yes, this was not a bug in vlcj but on the website and not hard to figure out thanks to the documentation.

**Comment by caprica** [comment]
That comment about the bug not being in vlcj was just a reminder for me.
