### ISSUE TITLE
Upload requires 8294400 elements, but only 8202240 elements remain in the buffer

### ISSUE THREAD

**Issue by androuino** [caprica/vlcj#904]
Hi,
I would like to ask some help about the error am having with **buffers**.
This is the code that am using:
https://gist.github.com/androuino/b573c497784b922a340c4fe716c9de89
then this is the error am getting:
`[pool-3-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaPlayerReady()
java.lang.IllegalArgumentException: Upload requires 8294400 elements, but only 8202240 elements remain in the buffer
	at com.sun.prism.impl.BaseTexture.checkUpdateParams(BaseTexture.java:385)
	at com.sun.prism.es2.ES2Texture.update(ES2Texture.java:640)
	at com.sun.prism.impl.BaseTexture.update(BaseTexture.java:321)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(BaseResourceFactory.java:224)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(BaseResourceFactory.java:152)
	at com.sun.javafx.sg.prism.NGImageView.renderContent(NGImageView.java:121)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGImageView.doRender(NGImageView.java:103)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:578)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:479)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:328)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:142)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

I am initializing the player by this code:

               videoSourceRatioProperty = SimpleFloatProperty(0.4f)
                canvas = Canvas()
                pixelWriter = canvas?.graphicsContext2D?.pixelWriter
                writablePixelFormat = PixelFormat.getByteBgraPreInstance()
                mediaPlayerComponent = CanvasPlayerComponent()
                mediaPlayerComponent?.mediaPlayer?.prepareMedia(file.absolutePath)
                mediaPlayerComponent?.mediaPlayer?.play()
                if (isContinuous) {
                    mediaPlayerComponent?.mediaPlayer?.repeat = true
                }

                groupMedia.children.add(imageView)

Although it's not crashing the javafx app but still kind of unconfortable to see these red warnings and am not sure if it has some effect on the long run but I would prefer a clean clode.
I hope someone could give me a shot on this. Thanks...

**Comment by caprica** [comment]
I have no idea about that code. Maybe the buffer format (chroma) is wrong.

Are you actually seeing properly decoded video frames, the correct colouring and so on?

**Comment by caprica** [comment]
This code:
```
 val y = stackPaneMain.height.minus(bufferFormat?.height!!).div(2).toInt()
                    pw!!.setPixels(
                        0,
                        y,
                        bufferFormat.width,
                        bufferFormat.height,
                        writablePixelFormat,
                        byteBuffer,
                        bufferFormat.pitches[0]
                    )
```
Are you sure it's OK to do that, i.e where you change the y-offset. It looks suspicious to me.

**Comment by androuino** [comment]
Yes I am still seeing the properly decoded video frames and correct coloring, the video looks fine but yeah, there's just this error always showing up.

And yes I intentionally did the computation for y-offset because if I don't do that, the video will be placed on top of the screen where X and Y is 0 and I don't want that because I want to show the video in the middle of the screen, that's why I did that computation but, if I set the offset to 0 for Y, the error doesn't show up, only if I set the Y offset greater than 0. Unless you have another way to properly show the video in the center of the screen. Thanks for the quick response btw.

**Comment by caprica** [comment]
Isn't your y-offset changing the position you're writing bytes to *within the buffer*. This might explain why unexpected buffer count message.

If you want to adjust the y-position of what you render, then it's the thing that contains the pixel buffer not the pixel buffer itself.

**Comment by caprica** [comment]
In any event, the suggestion is you're writing the wrong number of bytes into the buffer.

**Comment by caprica** [comment]
Maybe do some maths here:
 - subtract 8202240 from 8294400. 
 - divide the answer by the pitch (probably 4)
 - divide the answer by the width

Probably you end up with "y".

**Comment by caprica** [comment]
Oh, I skimmed over this in your comment:
> if I set the offset to 0 for Y, the error doesn't show up

This of course then is your answer.

And there are many ways to achieve what you want, but fundamentally you need to adjust the position of the thing that contains your pixel writer. How to do that is nothing at all to do with vlcj.

**Comment by androuino** [comment]
Ok, I will try to look at it again in a more in-depth way. Thanks.
