### ISSUE TITLE
stop() working asynchronously breaks due to subitems

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj#934]
New for VLC 4.x, media player stop() is asynchronous.

If you play media, then play media again, the second media may not start - seemingly because the first media is still in the process of stopping.

See if 5480b2c47aaa0d0fbb3771017b5e5e01dca923ed has any impact here.

**Comment by caprica** [comment]
Remember that stopped has some interplay with finished.

**Comment by caprica** [comment]
If you let the media finish, the next media works as expected - it is only when you play media when media is already playing, this will not work until you play media *again*.

**Comment by caprica** [comment]
May be related to resetting media, IIRC there is some intricate code in there, sometimes this new exception is observed:

```
ava.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@104ddf4e[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@73539951[Wrapped task = uk.co.caprica.vlcj.player.base.ResetMediaEventHandler$ResetMediaTask@3651095f]] rejected from java.util.concurrent.ThreadPoolExecutor@7ad9900[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:714)
	at uk.co.caprica.vlcj/uk.co.caprica.vlcj.support.eventmanager.TaskExecutor.submit(TaskExecutor.java:68)
	at uk.co.caprica.vlcj/uk.co.caprica.vlcj.player.base.MediaPlayer.submit(MediaPlayer.java:251)
	at uk.co.caprica.vlcj/uk.co.caprica.vlcj.player.base.ResetMediaEventHandler.finished(ResetMediaEventHandler.java:36)
	at uk.co.caprica.vlcj/uk.co.caprica.vlcj.player.base.events.MediaPlayerEndReachedEvent.notify(MediaPlayerEndReachedEvent.java:36)
	at uk.co.caprica.vlcj/uk.co.caprica.vlcj.player.base.events.MediaPlayerEndReachedEvent.notify(MediaPlayerEndReachedEvent.java:28)
	at uk.co.caprica.vlcj/uk.co.caprica.vlcj.support.eventmanager.NativeEventManager.raiseEvent(NativeEventManager.java:179)
	at uk.co.caprica.vlcj/uk.co.caprica.vlcj.support.eventmanager.NativeEventManager$EventCallback.callback(NativeEventManager.java:206)```

**Comment by caprica** [comment]
Similar issues around pause() maybe.

**Comment by caprica** [comment]
Need to take into account what happens if stop is called when the media is already stopped - in that case we couldn't rely on an event.

Might need to start tracking all events (internally) and maintaining an internal media player state - reluctant to do this.

**Comment by caprica** [comment]
When invoking stop_async, an End Reached event is raised - this kicks off its own special internal logic in vlcj which in turn invokes stop. Oh dear.

**Comment by caprica** [comment]
When the video ends normally, this is the sequence of events:

```
EVENT: libvlc_MediaPlayerEndReached
EVENT: libvlc_MediaPlayerVout
EVENT: libvlc_MediaPlayerESDeleted
EVENT: libvlc_MediaPlayerESDeleted
EVENT: libvlc_MediaPlayerStopped
```

So it looks like in both cases, when a video ends or is stopped, End Reached is always raised, then finally Stopped.

This is a Good Thing.

**Comment by caprica** [comment]
This does however break a fundamental concept in the "waiters" mini framework, it has bespoke handling for End Reached. This is kinda broken now.

This is a Bad Thing.

**Comment by caprica** [comment]
Interestingly, it looks like something intrinsic to vlcj's current implementation, as a bare-bones test allows play to be called multiple times in succession without any problem.

**Comment by caprica** [comment]
Ah. subitems my old friend. 

```
    private void applyMedia() {
        libvlc_media_t mediaInstance = media.mediaInstance();
        // Setting media is asynchronous
        libvlc_media_player_set_media(mediaPlayerInstance, mediaInstance);
//        mediaPlayer.subitems().changeMedia(mediaInstance); <---- this is now broken with VLC 4.x
    }
```

Removing the commented line above that deals with subitems appears to resolve the issue.

**Comment by caprica** [comment]
Summary:
1. subitem handling needs rework
2. the conditional "waiter" mini-framework needs rework due to assumptions about End Reached and Stopped events that are no longer true with VLC 4.x

**Comment by caprica** [comment]
Related c56e831b836b26f14780fb7d690912eb67be6bff.

**Comment by caprica** [comment]
Regarding the earlier comment in respect of invoking stop during `changeMedia`:
e61e6a4ca98c876c8e7302568c271fe81df5cebb

**Comment by caprica** [comment]
Confirmed that the vlcj YouTube player still works (with all of the above changes) without any further changes to subitem handling.

(Caveat: my VLC master build does not install the LUA playlist scripts, so for local testing create ~/.local/share/vlc/lua/playlist/ and copy the youtube*.lua* scripts there).

**Comment by caprica** [comment]
This just leaves the "waiter" rework, which will be done under a separate ticket #941.
