### ISSUE TITLE
Cannot load Vlcj on MacOS

### ISSUE THREAD

**Issue by martinisraelsen** [caprica/vlcj#971]
Try to get Vlcj to work on Mac without much luck.

NativeDiscovery crashes with NoSuchMethodError. Using macOS Catalina (10.15.5) and tried with both JDK 8 and JDK 11. Tried Vlcj 4.4.4 and 4.5.2.

Any suggestions to what might be wrong?

```
java.lang.NoSuchMethodError: 'com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class)'
	at uk.co.caprica.vlcj.binding.LibC.<clinit>(LibC.java:38)
	at uk.co.caprica.vlcj.factory.discovery.strategy.OsxNativeDiscoveryStrategy.setPluginPath(OsxNativeDiscoveryStrategy.java:72)
	at uk.co.caprica.vlcj.factory.discovery.strategy.BaseNativeDiscoveryStrategy.onSetPluginPath(BaseNativeDiscoveryStrategy.java:126)
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.tryPluginPath(NativeDiscovery.java:176)
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.discover(NativeDiscovery.java:117)
	at mtag.VlcjTest.test(VlcjTest.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)


```

Application

```
/**
 * 
 */
package mtag;

import org.junit.Test;
import uk.co.caprica.vlcj.factory.MediaPlayerFactory;
import uk.co.caprica.vlcj.factory.discovery.NativeDiscovery;
import uk.co.caprica.vlcj.media.Media;
import uk.co.caprica.vlcj.media.MediaEventAdapter;
import uk.co.caprica.vlcj.media.MediaParsedStatus;
import uk.co.caprica.vlcj.player.base.MediaPlayer;

/**
 * @author mi
 *
 */
public class VlcjTest {

   @Test
   public void test() {

      NativeDiscovery nd = new NativeDiscovery();
      if (!nd.discover()) {
         System.out.println("VLC not found");
      }

      MediaPlayerFactory factory = new MediaPlayerFactory();
      MediaPlayer mp = factory.mediaPlayers().newMediaPlayer();

      mp.events().addMediaEventListener(new MediaEventAdapter() {

         @Override
         public void mediaParsedChanged(Media media, MediaParsedStatus newStatus) {
            super.mediaParsedChanged(media, newStatus);
         }
      }

      );

      mp.media().prepare("/Volumes/global/intro.m4v");
      mp.media().parsing().parse();
   }
}

```

**Comment by caprica** [comment]
Forget vlcj 4.5.x.

IIRC someone before had a problem like this on macOS and it was because there was an old version of JNA on the classpath somehow.

**Comment by ivanooi** [comment]
sorry, I didn;t know that. 1st time to do so...

**Comment by caprica** [comment]
Nothing to be sorry about! Just FYI vlcj 4.5.x is discontinued, it used Java Modules and it was frankly a PITA so I dropped it. This means 4.4.x is currently the latest version you should use.

Did you check if an old version of JNA was installed on your system somehow?

**Comment by caprica** [comment]
@ivanooi I found some time to take a look at your changes and have some comments

1. Yes, the API for "attach" did change so removing the libvlc parameter is fine
2. I tested the code as is, and it still works using the embedded handle field, so why is the reflection code you added needed?

**Comment by ivanooi** [comment]
sorry for my late reply. I just finished meeting. Current code do not work with the latest SWT. I'm using SWT version 4.9. Windows is ok but not for Mac.

so, you check this photo. Composite no more exposed handle. 
![image](https://user-images.githubusercontent.com/15061028/84596409-33743980-ae90-11ea-82f2-d9b542b1004c.png)

a better one should be like this. sorry , as I'm not very getting used to Git : 

`    private long getControlHandle(Control c){
    	long handle = 0;
    	Field _idField = null ;
    	try {
    		
    		String ls_os = System.getProperty("os.name").toLowerCase();
    		
    		if( ls_os.indexOf("win") != -1 ) {
    			
        		_idField = Control.class.getDeclaredField("handle");
        		handle = _idField.getLong(c);          
    		}else
    		if( ls_os.indexOf("mac") != -1 ) {
    			
        		Class<?>idClass = Class.forName("org.eclipse.swt.internal.cocoa.id");
        		_idField = idClass.getDeclaredField("id");
        		Field _viewField = Control.class.getDeclaredField("view");                    
        		Object view = _viewField.get(c);                    
        		handle = _idField.getLong(view);
    		}
    	}
    	catch(Exception e){
    		e.printStackTrace();
    	}
    	return handle;
    }
`

**Comment by caprica** [comment]
Is 4.9 available in any public maven repository?

And please stop apologising, it's all good :-)

**Comment by caprica** [comment]
In your code fragment, there should be a clause for Linux, not just Windows and macOS.

**Comment by caprica** [comment]
Just for reference for anyone else reading this, this issue has been accidentally hijacked from OP's report about not working on macOS.

The rest of the comments follow from #972 

Reminder to self to clean up this history later.

**Comment by ivanooi** [comment]
> In your code fragment, there should be a clause for Linux, not just Windows and macOS.

I only have Mac and Win. I believe the Win section should work for Linux as well.

_idField = Control.class.getDeclaredField("handle");
handle = _idField.getLong(c);

**Comment by ivanooi** [comment]
> Is 4.9 available in any public maven repository?
> 
> And please stop apologising, it's all good :-)

This is the link : 
https://archive.eclipse.org/eclipse/downloads/drops4/R-4.9-201809060745/

build 4.9 is the last build that supports Win32 bit. 

Thanks again :-)

**Comment by ivanooi** [comment]
Just share some code how to load VLC for Mac and Win :-P. 
Mac : 
`        is_path = "/Volumes/TzuChi3in1/tzuchi(I)/vlcj-swt-master/VLC-3.0.10";
        
        NativeLibrary.addSearchPath("vlc", is_path  + "/lib");
        LibC.INSTANCE.setenv("VLC_PLUGIN_PATH", is_path + "/plugins", 1);        
`
Win : 
`
       NativeLibrary.addSearchPath("libvlc", is_path );
      LibC.INSTANCE._putenv("VLC_PLUGIN_PATH=" + is_path + "\\plugins");
`

**Comment by ivanooi** [comment]
> Nothing to be sorry about! Just FYI vlcj 4.5.x is discontinued, it used Java Modules and it was frankly a PITA so I dropped it. This means 4.4.x is currently the latest version you should use.
> 
> Did you check if an old version of JNA was installed on your system somehow?

oh? Not going to support VLC 4? I found VLC3 not quite stable under Win10. Crash a lot...

**Comment by caprica** [comment]
vlcj-5.x will be for VLC 4, and it already works very well.

The reason I abandoned vlcj 4.5.x is because I properly implemented the Java Module System and frankly the Java Module System is a colossal PITA so I stopped. vlcj 4.4.x is still current.

**Comment by ivanooi** [comment]
I just checked maven repository ,i can't find VLCJ5 there.is it I need to compile myself? 
Thanks

**Comment by caprica** [comment]
@ivanooi Yes you do need to compile it yourself.

Also, please don't keep posting random comments on the same issue. I am going to clean up (delete) the comments in this issue now because they're not relevant to the OP.

**Comment by caprica** [comment]
Closing due to lack of follow-up, it can be re-opened if more information is provided.
