### ISSUE TITLE
Caused by: java.lang.RuntimeException: Failed to get a new native library instance

### ISSUE THREAD

**Issue by XDIYIBEIZI-XH** [caprica/vlcj#982]
First, when I installed the VLC player, the project worked fine.

However, when I uninstall the VLC player, I put libvlc.dll livblccore.dll in the project directory. It can be loaded into a DLL file, but failed to create an instance of the player.

vlcj             : 4.4.2
os               : Windows 10 10.0 amd64
java             : 1.8.0_172 Oracle Corporation
java.home        : D:\Java\jdk1.8.0_172\jre
jna.library.path : <not set>
java.library.path: D:\Java\jdk1.8.0_172\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;D:/Java/jdk1.8.0_172/bin/../jre/bin/server;D:/Java/jdk1.8.0_172/bin/../jre/bin;D:/Java/jdk1.8.0_172/bin/../jre/lib/amd64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Java\jdk1.8.0_172\bin;C:\Users\kaifabu\AppData\Local\Microsoft\WindowsApps;;D:\DriverGenius;D:\DriverGenius\ksoft;F:\eclipse;;.
PATH             : D:/Java/jdk1.8.0_172/bin/../jre/bin/server;D:/Java/jdk1.8.0_172/bin/../jre/bin;D:/Java/jdk1.8.0_172/bin/../jre/lib/amd64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Java\jdk1.8.0_172\bin;C:\Users\kaifabu\AppData\Local\Microsoft\WindowsApps;;D:\DriverGenius;D:\DriverGenius\ksoft;F:\eclipse;
VLC_PLUGIN_PATH  : <not set>
Exception in thread "main" java.lang.ExceptionInInitializerError
	at uk.co.caprica.vlcjplayer.Application.application(Application.java:74)
	at uk.co.caprica.vlcjplayer.VlcjPlayer.<init>(VlcjPlayer.java:148)
	at uk.co.caprica.vlcjplayer.VlcjPlayer.main(VlcjPlayer.java:121)
Caused by: java.lang.RuntimeException: Failed to get a new native library instance
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.newLibVlcInstance(MediaPlayerFactory.java:214)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:110)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132)
	at uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent.initMediaPlayerFactory(EmbeddedMediaPlayerComponent.java:116)
	at uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent.<init>(EmbeddedMediaPlayerComponent.java:77)
	at uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent.<init>(EmbeddedMediaPlayerComponent.java:111)
	at uk.co.caprica.vlcjplayer.Application.<init>(Application.java:84)
	at uk.co.caprica.vlcjplayer.Application.<init>(Application.java:81)
	at uk.co.caprica.vlcjplayer.Application$ApplicationHolder.<clinit>(Application.java:70)
	... 3 more

**Comment by XDIYIBEIZI-XH** [comment]
Ok, that's done, I've put the plug-in files back in the project directory. It worked.

There are some out-of-date plug-ins. I don't know if it's normal.

[0000029140f915e0] main libvlc error: stale plugins cache: modified F:\eclipse\workspace\clip\plugins\codec\librawvideo_plugin.dll
[0000029140f915e0] main libvlc error: stale plugins cache: modified F:\eclipse\workspace\clip\plugins\codec\librtpvideo_plugin.dll
[0000029140f915e0] main libvlc error: stale plugins cache: modified F:\eclipse\workspace\clip\plugins\codec\libschroedinger_plugin.dll
[0000029140f915e0] main libvlc error: stale plugins cache: modified F:\eclipse\workspace\clip\plugins\codec\libscte18_plugin.dll
[0000029140f915e0] main libvlc error: stale plugins cache: modified F:\eclipse\workspace\clip\plugins\codec\libscte27_plugin.dll
[0000029140f915e0] main libvlc error: stale plugins cache: modified F:\eclipse\workspace\clip\plugins\codec\libsdl_image_plugin.dll
[0000029140f915e0] main libvlc error: stale plugins cache: modified F:\eclipse\workspace\clip\plugins\codec\libspdif_plugin.dll
[0000029140f915e0] main libvlc error: stale plugins cache: modified F:\eclipse\workspace\clip\plugins\codec\libspeex_plugin.dll

**Comment by XDIYIBEIZI-XH** [comment]
Although the above method can run normally, but the CPU utilization rate is high, causing the project to run very slow.

**Comment by XDIYIBEIZI-XH** [comment]
Sorry, it's my program problem. It has nothing to do with the plug-in library.
